# ExifTool synchronization configuration

[exiftool]
version = "13.26"
git_commit = "unknown"  # TODO: Add actual commit hash
last_sync = "2025-06-24"
source_path = "third-party/exiftool"

[sync_status]
fully_incorporated = []
partially_incorporated = {}
pending = ["13.26"]

[module_versions]
"src/maker/canon" = "13.26"
"src/maker/nikon" = "13.26"
"src/maker/sony" = "13.26"
"src/maker/fujifilm" = "13.26"
"src/maker/olympus" = "13.26"
"src/maker/pentax" = "13.26"
"src/maker/samsung" = "13.26"
"src/maker/sigma" = "13.26"

# Algorithm extraction tracking
[extraction]
binary_formats = { source = "multiple", last_extracted = "13.26", timestamp = "2025-06-24" }
magic_numbers = { source = "ExifTool.pm:912-1027", last_extracted = "13.26", timestamp = "2025-06-24" }
datetime_patterns = { source = "multiple", last_extracted = "pending" }
binary_tags = { source = "Exif.pm:4858-4877", last_extracted = "pending" }
writable_tags = { source = "lib/Image/ExifTool/*.pm", last_extracted = "13.26", timestamp = "2025-06-25" }

[algorithm_tracking]
"ProcessBinaryData" = { version = "13.26", modules = ["Canon.pm", "Nikon.pm", "Sony.pm", "Fujifilm.pm", "Olympus.pm", "Pentax.pm", "Panasonic.pm", "Samsung.pm", "Sigma.pm"] }

# Track which versions we've fully reviewed
[sync_history]
fully_synced = []  # Will be populated as we complete full synchronizations