//! Auto-generated fujifilm tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/FujiFilm.pm
//! EXIFTOOL-VERSION: 12.65
//!
//! This file is auto-generated by exiftool_sync extract printconv-tables.
//! Do not edit manually.

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/FujiFilm.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)] // Allow ExifTool-style naming
pub struct FUJIFILMTag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// FujiFilm tag definitions with PrintConv mappings
pub const FUJIFILM_TAGS: &[FUJIFILMTag] = &[
    FUJIFILMTag {
        id: 0x0000,
        name: "Version",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x0010,
        name: "InternalSerialNumber",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1000,
        name: "Quality",
        print_conv: PrintConvId::Quality,
    },
    FUJIFILMTag {
        id: 0x1001,
        name: "Sharpness",
        print_conv: PrintConvId::UniversalParameter,
    },
    FUJIFILMTag {
        id: 0x1002,
        name: "WhiteBalance",
        print_conv: PrintConvId::WhiteBalance,
    },
    FUJIFILMTag {
        id: 0x1003,
        name: "Saturation",
        print_conv: PrintConvId::UniversalParameter,
    },
    FUJIFILMTag {
        id: 0x1004,
        name: "Contrast",
        print_conv: PrintConvId::UniversalParameter,
    },
    FUJIFILMTag {
        id: 0x1005,
        name: "ColorTemperature",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1006,
        name: "Contrast",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x100a,
        name: "WhiteBalanceFineTune",
        print_conv: PrintConvId::WhiteBalance,
    },
    FUJIFILMTag {
        id: 0x100b,
        name: "NoiseReduction",
        print_conv: PrintConvId::UniversalNoiseReduction,
    },
    FUJIFILMTag {
        id: 0x100e,
        name: "NoiseReduction",
        print_conv: PrintConvId::UniversalNoiseReduction,
    },
    FUJIFILMTag {
        id: 0x100f,
        name: "Clarity",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1010,
        name: "FujiFlashMode",
        print_conv: PrintConvId::FlashMode,
    },
    FUJIFILMTag {
        id: 0x1011,
        name: "FlashExposureComp",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1020,
        name: "Macro",
        print_conv: PrintConvId::OnOff,
    },
    FUJIFILMTag {
        id: 0x1021,
        name: "FocusMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1022,
        name: "AFMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x102b,
        name: "PrioritySettings",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x102d,
        name: "FocusSettings",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x102e,
        name: "AFCSettings",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1023,
        name: "FocusPixel",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1030,
        name: "SlowSync",
        print_conv: PrintConvId::OnOff,
    },
    FUJIFILMTag {
        id: 0x1031,
        name: "PictureMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1032,
        name: "ExposureCount",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1033,
        name: "EXRAuto",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1034,
        name: "EXRMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1040,
        name: "ShadowTone",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1041,
        name: "HighlightTone",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1044,
        name: "DigitalZoom",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1045,
        name: "LensModulationOptimizer",
        print_conv: PrintConvId::OnOff,
    },
    FUJIFILMTag {
        id: 0x1047,
        name: "GrainEffectRoughness",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1048,
        name: "ColorChromeEffect",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1049,
        name: "BWAdjustment",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x104b,
        name: "BWMagentaGreen",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x104d,
        name: "CropMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x104e,
        name: "ColorChromeFXBlue",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1050,
        name: "ShutterType",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1051,
        name: "CropFlag",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1052,
        name: "CropTopLeft",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1053,
        name: "CropSize",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1101,
        name: "SequenceNumber",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1103,
        name: "DriveSettings",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1105,
        name: "PixelShiftShots",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1106,
        name: "PixelShiftOffset",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1153,
        name: "PanoramaAngle",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1154,
        name: "PanoramaDirection",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1201,
        name: "AdvancedFilter",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1210,
        name: "ColorMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1300,
        name: "BlurWarning",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1301,
        name: "FocusWarning",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1302,
        name: "ExposureWarning",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1304,
        name: "GEImageSize",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1400,
        name: "DynamicRange",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1401,
        name: "FilmMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1402,
        name: "DynamicRangeSetting",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1403,
        name: "DevelopmentDynamicRange",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1404,
        name: "MinFocalLength",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1405,
        name: "MaxFocalLength",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1406,
        name: "MaxApertureAtMinFocal",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1407,
        name: "MaxApertureAtMaxFocal",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x140b,
        name: "AutoDynamicRange",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1422,
        name: "ImageStabilization",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1425,
        name: "SceneRecognition",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1431,
        name: "Rating",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1436,
        name: "ImageGeneration",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1438,
        name: "ImageCount",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1443,
        name: "DRangePriority",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1444,
        name: "DRangePriorityAuto",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1445,
        name: "DRangePriorityFixed",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1446,
        name: "FlickerReduction",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1447,
        name: "FujiModel",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x1448,
        name: "FujiModel2",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x144d,
        name: "RollAngle",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3803,
        name: "VideoRecordingMode",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3804,
        name: "PeripheralLighting",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3806,
        name: "VideoCompression",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3820,
        name: "FrameRate",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3821,
        name: "FrameWidth",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3822,
        name: "FrameHeight",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x3824,
        name: "FullHDHighSpeedRec",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4005,
        name: "FaceElementSelected",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4100,
        name: "FacesDetected",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4103,
        name: "FacePositions",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4200,
        name: "NumFaceElements",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4201,
        name: "FaceElementTypes",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4203,
        name: "FaceElementPositions",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x4282,
        name: "FaceRecInfo",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x8000,
        name: "FileSource",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x8002,
        name: "OrderNumber",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0x8003,
        name: "FrameNumber",
        print_conv: PrintConvId::None,
    },
    FUJIFILMTag {
        id: 0xb211,
        name: "Parallax",
        print_conv: PrintConvId::None,
    },
];

/// Get fujifilm tag by ID
pub fn get_fujifilm_tag(tag_id: u16) -> Option<&'static FUJIFILMTag> {
    FUJIFILM_TAGS.iter().find(|tag| tag.id == tag_id)
}
