//! Auto-generated stub gopro tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/GoPro.pm
//! This is a stub file generated when no data was found.
//! Regenerate with: cargo run --bin exiftool_sync extract printconv-tables GoPro.pm

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/GoPro.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)] // Allow ExifTool-style naming
pub struct GOPROTag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// Stub tag table (empty - regenerate to populate)
pub const GOPRO_TAGS: &[GOPROTag] = &[
    // Stub - real tags will be generated by extractor
];

/// Get gopro tag by ID
pub fn get_gopro_tag(tag_id: u16) -> Option<&'static GOPROTag> {
    GOPRO_TAGS.iter().find(|tag| tag.id == tag_id)
}
