//! Auto-generated kodak tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/Kodak.pm
//! EXIFTOOL-VERSION: 12.65
//!
//! This file is auto-generated by exiftool_sync extract printconv-tables.
//! Do not edit manually.

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Kodak.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)] // Allow ExifTool-style naming
pub struct KODAKTag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// Kodak tag definitions with PrintConv mappings
pub const KODAK_TAGS: &[KODAKTag] = &[
    KODAKTag {
        id: 0x0000,
        name: "KodakModel",
        print_conv: PrintConvId::KodakModelLookup,
    },
    KODAKTag {
        id: 0x0009,
        name: "Quality",
        print_conv: PrintConvId::Quality,
    },
    KODAKTag {
        id: 0x000a,
        name: "BurstMode",
        print_conv: PrintConvId::OnOff,
    },
    KODAKTag {
        id: 0x000c,
        name: "KodakImageWidth",
        print_conv: PrintConvId::KodakKodakImageWidth,
    },
    KODAKTag {
        id: 0x000e,
        name: "KodakImageHeight",
        print_conv: PrintConvId::KodakKodakImageHeight,
    },
    KODAKTag {
        id: 0x0010,
        name: "YearCreated",
        print_conv: PrintConvId::KodakYearCreated,
    },
    KODAKTag {
        id: 0x0012,
        name: "MonthDayCreated",
        print_conv: PrintConvId::KodakMonthDayCreated,
    },
    KODAKTag {
        id: 0x0014,
        name: "TimeCreated",
        print_conv: PrintConvId::KodakTimeCreated,
    },
    KODAKTag {
        id: 0x0018,
        name: "BurstMode2",
        print_conv: PrintConvId::KodakBurstMode2,
    },
    KODAKTag {
        id: 0x001b,
        name: "ShutterMode",
        print_conv: PrintConvId::KodakShutterMode,
    },
    KODAKTag {
        id: 0x001c,
        name: "MeteringMode",
        print_conv: PrintConvId::MeteringMode,
    },
    KODAKTag {
        id: 0x001e,
        name: "FNumber",
        print_conv: PrintConvId::KodakFNumber,
    },
    KODAKTag {
        id: 0x0020,
        name: "ExposureTime",
        print_conv: PrintConvId::KodakExposureTime,
    },
    KODAKTag {
        id: 0x0024,
        name: "ExposureCompensation",
        print_conv: PrintConvId::KodakExposureCompensation,
    },
    KODAKTag {
        id: 0x0026,
        name: "VariousModes",
        print_conv: PrintConvId::KodakVariousModes,
    },
    KODAKTag {
        id: 0x0028,
        name: "Distance1",
        print_conv: PrintConvId::KodakDistance1,
    },
    KODAKTag {
        id: 0x002c,
        name: "Distance2",
        print_conv: PrintConvId::KodakDistance2,
    },
    KODAKTag {
        id: 0x0030,
        name: "Distance3",
        print_conv: PrintConvId::KodakDistance3,
    },
    KODAKTag {
        id: 0x0034,
        name: "Distance4",
        print_conv: PrintConvId::KodakDistance4,
    },
    KODAKTag {
        id: 0x0038,
        name: "FocusMode",
        print_conv: PrintConvId::KodakFocusMode,
    },
    KODAKTag {
        id: 0x003a,
        name: "VariousModes2",
        print_conv: PrintConvId::KodakVariousModes2,
    },
    KODAKTag {
        id: 0x003c,
        name: "PanoramaMode",
        print_conv: PrintConvId::KodakPanoramaMode,
    },
    KODAKTag {
        id: 0x003e,
        name: "SubjectDistance",
        print_conv: PrintConvId::KodakSubjectDistance,
    },
    KODAKTag {
        id: 0x0040,
        name: "WhiteBalance",
        print_conv: PrintConvId::WhiteBalance,
    },
    KODAKTag {
        id: 0x005c,
        name: "FlashMode",
        print_conv: PrintConvId::FlashMode,
    },
    KODAKTag {
        id: 0x005d,
        name: "FlashFired",
        print_conv: PrintConvId::YesNo,
    },
    KODAKTag {
        id: 0x005e,
        name: "ISOSetting",
        print_conv: PrintConvId::KodakISOSetting,
    },
    KODAKTag {
        id: 0x0060,
        name: "ISO",
        print_conv: PrintConvId::KodakISO,
    },
    KODAKTag {
        id: 0x0062,
        name: "TotalZoom",
        print_conv: PrintConvId::KodakTotalZoom,
    },
    KODAKTag {
        id: 0x0064,
        name: "DateTimeStamp",
        print_conv: PrintConvId::KodakDateTimeStamp,
    },
    KODAKTag {
        id: 0x0066,
        name: "ColorMode",
        print_conv: PrintConvId::KodakColorMode,
    },
    KODAKTag {
        id: 0x0068,
        name: "DigitalZoom",
        print_conv: PrintConvId::KodakDigitalZoom,
    },
    KODAKTag {
        id: 0x006b,
        name: "Sharpness",
        print_conv: PrintConvId::KodakSharpness,
    },
];

/// Get kodak tag by ID
pub fn get_kodak_tag(tag_id: u16) -> Option<&'static KODAKTag> {
    KODAK_TAGS.iter().find(|tag| tag.id == tag_id)
}
