//! Auto-generated minolta tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/Minolta.pm
//! EXIFTOOL-VERSION: 12.65
//!
//! This file is auto-generated by exiftool_sync extract printconv-tables.
//! Do not edit manually.

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Minolta.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)] // Allow ExifTool-style naming
pub struct MINOLTATag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// Minolta tag definitions with PrintConv mappings
pub const MINOLTA_TAGS: &[MINOLTATag] = &[
    MINOLTATag {
        id: 0x0000,
        name: "MakerNoteVersion",
        print_conv: PrintConvId::MinoltaMakerNoteVersion,
    },
    MINOLTATag {
        id: 0x0001,
        name: "MinoltaCameraSettingsOld",
        print_conv: PrintConvId::MinoltaMinoltaCameraSettingsOld,
    },
    MINOLTATag {
        id: 0x0003,
        name: "MinoltaCameraSettings",
        print_conv: PrintConvId::MinoltaMinoltaCameraSettings,
    },
    MINOLTATag {
        id: 0x0004,
        name: "MinoltaCameraSettings7D",
        print_conv: PrintConvId::MinoltaMinoltaCameraSettings7D,
    },
    MINOLTATag {
        id: 0x0010,
        name: "CameraInfoA100",
        print_conv: PrintConvId::MinoltaCameraInfoA100,
    },
    MINOLTATag {
        id: 0x0020,
        name: "WBInfoA100",
        print_conv: PrintConvId::MinoltaWBInfoA100,
    },
    MINOLTATag {
        id: 0x0040,
        name: "CompressedImageSize",
        print_conv: PrintConvId::MinoltaCompressedImageSize,
    },
    MINOLTATag {
        id: 0x0088,
        name: "PreviewImageStart",
        print_conv: PrintConvId::MinoltaPreviewImageStart,
    },
    MINOLTATag {
        id: 0x0089,
        name: "PreviewImageLength",
        print_conv: PrintConvId::MinoltaPreviewImageLength,
    },
    MINOLTATag {
        id: 0x0100,
        name: "SceneMode",
        print_conv: PrintConvId::MinoltaSceneMode,
    },
    MINOLTATag {
        id: 0x0102,
        name: "MinoltaQuality",
        print_conv: PrintConvId::Quality,
    },
    MINOLTATag {
        id: 0x0104,
        name: "FlashExposureComp",
        print_conv: PrintConvId::MinoltaFlashExposureComp,
    },
    MINOLTATag {
        id: 0x0105,
        name: "Teleconverter",
        print_conv: PrintConvId::MinoltaTeleconverter,
    },
    MINOLTATag {
        id: 0x0107,
        name: "ImageStabilization",
        print_conv: PrintConvId::MinoltaImageStabilization,
    },
    MINOLTATag {
        id: 0x0109,
        name: "RawAndJpgRecording",
        print_conv: PrintConvId::OnOff,
    },
    MINOLTATag {
        id: 0x010a,
        name: "ZoneMatching",
        print_conv: PrintConvId::MinoltaZoneMatching,
    },
    MINOLTATag {
        id: 0x010b,
        name: "ColorTemperature",
        print_conv: PrintConvId::MinoltaColorTemperature,
    },
    MINOLTATag {
        id: 0x010c,
        name: "LensType",
        print_conv: PrintConvId::MinoltaMinoltaLensTypes,
    },
    MINOLTATag {
        id: 0x0111,
        name: "ColorCompensationFilter",
        print_conv: PrintConvId::MinoltaColorCompensationFilter,
    },
    MINOLTATag {
        id: 0x0112,
        name: "WhiteBalanceFineTune",
        print_conv: PrintConvId::WhiteBalance,
    },
    MINOLTATag {
        id: 0x0113,
        name: "ImageStabilization",
        print_conv: PrintConvId::MinoltaImageStabilization,
    },
    MINOLTATag {
        id: 0x0115,
        name: "WhiteBalance",
        print_conv: PrintConvId::WhiteBalance,
    },
    MINOLTATag {
        id: 0x0e00,
        name: "PrintIM",
        print_conv: PrintConvId::MinoltaPrintIM,
    },
    MINOLTATag {
        id: 0x0f00,
        name: "MinoltaCameraSettings2",
        print_conv: PrintConvId::MinoltaMinoltaCameraSettings2,
    },
];

/// Get minolta tag by ID
pub fn get_minolta_tag(tag_id: u16) -> Option<&'static MINOLTATag> {
    MINOLTA_TAGS.iter().find(|tag| tag.id == tag_id)
}
