//! Auto-generated nikon tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/Nikon.pm
//! EXIFTOOL-VERSION: 12.65
//!
//! This file is auto-generated by exiftool_sync extract printconv-tables.
//! Do not edit manually.

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Nikon.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)] // Allow ExifTool-style naming
pub struct NIKONTag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// Nikon tag definitions with PrintConv mappings
pub const NIKON_TAGS: &[NIKONTag] = &[
    NIKONTag {
        id: 0x0001,
        name: "MakerNoteVersion",
        print_conv: PrintConvId::NikonMakerNoteVersion,
    },
    NIKONTag {
        id: 0x0002,
        name: "ISO",
        print_conv: PrintConvId::NikonISO,
    },
    NIKONTag {
        id: 0x0003,
        name: "ColorMode",
        print_conv: PrintConvId::NikonColorMode,
    },
    NIKONTag {
        id: 0x0004,
        name: "Quality",
        print_conv: PrintConvId::Quality,
    },
    NIKONTag {
        id: 0x0005,
        name: "WhiteBalance",
        print_conv: PrintConvId::WhiteBalance,
    },
    NIKONTag {
        id: 0x0006,
        name: "Sharpness",
        print_conv: PrintConvId::NikonSharpness,
    },
    NIKONTag {
        id: 0x0007,
        name: "FocusMode",
        print_conv: PrintConvId::NikonFocusMode,
    },
    NIKONTag {
        id: 0x0008,
        name: "FlashSetting",
        print_conv: PrintConvId::NikonFlashSetting,
    },
    NIKONTag {
        id: 0x0009,
        name: "FlashType",
        print_conv: PrintConvId::NikonFlashType,
    },
    NIKONTag {
        id: 0x000b,
        name: "WhiteBalanceFineTune",
        print_conv: PrintConvId::WhiteBalance,
    },
    NIKONTag {
        id: 0x000c,
        name: "WB_RBLevels",
        print_conv: PrintConvId::NikonWB_RBLevels,
    },
    NIKONTag {
        id: 0x000d,
        name: "ProgramShift",
        print_conv: PrintConvId::NikonProgramShift,
    },
    NIKONTag {
        id: 0x000e,
        name: "ExposureDifference",
        print_conv: PrintConvId::NikonExposureDifference,
    },
    NIKONTag {
        id: 0x000f,
        name: "ISOSelection",
        print_conv: PrintConvId::NikonISOSelection,
    },
    NIKONTag {
        id: 0x0010,
        name: "DataDump",
        print_conv: PrintConvId::NikonDataDump,
    },
    NIKONTag {
        id: 0x0011,
        name: "PreviewIFD",
        print_conv: PrintConvId::NikonPreviewIFD,
    },
    NIKONTag {
        id: 0x0012,
        name: "FlashExposureComp",
        print_conv: PrintConvId::NikonFlashExposureComp,
    },
    NIKONTag {
        id: 0x0013,
        name: "ISOSetting",
        print_conv: PrintConvId::NikonISOSetting,
    },
    NIKONTag {
        id: 0x0016,
        name: "ImageBoundary",
        print_conv: PrintConvId::NikonImageBoundary,
    },
    NIKONTag {
        id: 0x0017,
        name: "ExternalFlashExposureComp",
        print_conv: PrintConvId::NikonExternalFlashExposureComp,
    },
    NIKONTag {
        id: 0x0018,
        name: "FlashExposureBracketValue",
        print_conv: PrintConvId::NikonFlashExposureBracketValue,
    },
    NIKONTag {
        id: 0x0019,
        name: "ExposureBracketValue",
        print_conv: PrintConvId::NikonExposureBracketValue,
    },
    NIKONTag {
        id: 0x001a,
        name: "ImageProcessing",
        print_conv: PrintConvId::NikonImageProcessing,
    },
    NIKONTag {
        id: 0x001b,
        name: "CropHiSpeed",
        print_conv: PrintConvId::NikonCropHiSpeed,
    },
    NIKONTag {
        id: 0x001c,
        name: "ExposureTuning",
        print_conv: PrintConvId::NikonExposureTuning,
    },
    NIKONTag {
        id: 0x001d,
        name: "SerialNumber",
        print_conv: PrintConvId::NikonSerialNumber,
    },
    NIKONTag {
        id: 0x001e,
        name: "ColorSpace",
        print_conv: PrintConvId::NikonColorSpace,
    },
    NIKONTag {
        id: 0x001f,
        name: "VRInfo",
        print_conv: PrintConvId::NikonVRInfo,
    },
    NIKONTag {
        id: 0x0020,
        name: "ImageAuthentication",
        print_conv: PrintConvId::OnOff,
    },
    NIKONTag {
        id: 0x0021,
        name: "FaceDetect",
        print_conv: PrintConvId::NikonFaceDetect,
    },
    NIKONTag {
        id: 0x0022,
        name: "ActiveD-Lighting",
        print_conv: PrintConvId::NikonActiveD_Lighting,
    },
    NIKONTag {
        id: 0x0024,
        name: "WorldTime",
        print_conv: PrintConvId::NikonWorldTime,
    },
    NIKONTag {
        id: 0x0025,
        name: "ISOInfo",
        print_conv: PrintConvId::NikonISOInfo,
    },
    NIKONTag {
        id: 0x002a,
        name: "VignetteControl",
        print_conv: PrintConvId::NikonVignetteControl,
    },
    NIKONTag {
        id: 0x002b,
        name: "DistortInfo",
        print_conv: PrintConvId::NikonDistortInfo,
    },
    NIKONTag {
        id: 0x002c,
        name: "UnknownInfo",
        print_conv: PrintConvId::NikonUnknownInfo,
    },
    NIKONTag {
        id: 0x0032,
        name: "UnknownInfo2",
        print_conv: PrintConvId::NikonUnknownInfo2,
    },
    NIKONTag {
        id: 0x0034,
        name: "ShutterMode",
        print_conv: PrintConvId::NikonShutterMode,
    },
    NIKONTag {
        id: 0x0037,
        name: "MechanicalShutterCount",
        print_conv: PrintConvId::NikonMechanicalShutterCount,
    },
    NIKONTag {
        id: 0x0039,
        name: "LocationInfo",
        print_conv: PrintConvId::NikonLocationInfo,
    },
    NIKONTag {
        id: 0x003d,
        name: "BlackLevel",
        print_conv: PrintConvId::NikonBlackLevel,
    },
    NIKONTag {
        id: 0x003e,
        name: "ImageSizeRAW",
        print_conv: PrintConvId::NikonImageSizeRAW,
    },
    NIKONTag {
        id: 0x003f,
        name: "WhiteBalanceFineTune",
        print_conv: PrintConvId::WhiteBalance,
    },
    NIKONTag {
        id: 0x0044,
        name: "JPGCompression",
        print_conv: PrintConvId::NikonJPGCompression,
    },
    NIKONTag {
        id: 0x0045,
        name: "CropArea",
        print_conv: PrintConvId::NikonCropArea,
    },
    NIKONTag {
        id: 0x004e,
        name: "NikonSettings",
        print_conv: PrintConvId::NikonNikonSettings,
    },
    NIKONTag {
        id: 0x004f,
        name: "ColorTemperatureAuto",
        print_conv: PrintConvId::NikonColorTemperatureAuto,
    },
    NIKONTag {
        id: 0x0051,
        name: "MakerNotes0x51",
        print_conv: PrintConvId::NikonMakerNotes0x51,
    },
    NIKONTag {
        id: 0x0056,
        name: "MakerNotes0x56",
        print_conv: PrintConvId::NikonMakerNotes0x56,
    },
    NIKONTag {
        id: 0x0080,
        name: "ImageAdjustment",
        print_conv: PrintConvId::NikonImageAdjustment,
    },
    NIKONTag {
        id: 0x0081,
        name: "ToneComp",
        print_conv: PrintConvId::NikonToneComp,
    },
    NIKONTag {
        id: 0x0082,
        name: "AuxiliaryLens",
        print_conv: PrintConvId::NikonLensType,
    },
    NIKONTag {
        id: 0x0083,
        name: "LensType",
        print_conv: PrintConvId::NikonLensType,
    },
    NIKONTag {
        id: 0x0085,
        name: "ManualFocusDistance",
        print_conv: PrintConvId::NikonManualFocusDistance,
    },
    NIKONTag {
        id: 0x0086,
        name: "DigitalZoom",
        print_conv: PrintConvId::NikonDigitalZoom,
    },
    NIKONTag {
        id: 0x0087,
        name: "FlashMode",
        print_conv: PrintConvId::FlashMode,
    },
    NIKONTag {
        id: 0x0089,
        name: "ShootingMode",
        print_conv: PrintConvId::NikonShootingMode,
    },
    NIKONTag {
        id: 0x008b,
        name: "LensFStops",
        print_conv: PrintConvId::NikonLensType,
    },
    NIKONTag {
        id: 0x008c,
        name: "ContrastCurve",
        print_conv: PrintConvId::NikonContrastCurve,
    },
    NIKONTag {
        id: 0x008d,
        name: "ColorHue",
        print_conv: PrintConvId::NikonColorHue,
    },
    NIKONTag {
        id: 0x008f,
        name: "SceneMode",
        print_conv: PrintConvId::NikonSceneMode,
    },
    NIKONTag {
        id: 0x0090,
        name: "LightSource",
        print_conv: PrintConvId::NikonLightSource,
    },
    NIKONTag {
        id: 0x0092,
        name: "HueAdjustment",
        print_conv: PrintConvId::NikonHueAdjustment,
    },
    NIKONTag {
        id: 0x0093,
        name: "NEFCompression",
        print_conv: PrintConvId::NikonNefCompression,
    },
    NIKONTag {
        id: 0x0094,
        name: "SaturationAdj",
        print_conv: PrintConvId::NikonSaturationAdj,
    },
    NIKONTag {
        id: 0x0095,
        name: "NoiseReduction",
        print_conv: PrintConvId::NikonNoiseReduction,
    },
    NIKONTag {
        id: 0x0096,
        name: "NEFLinearizationTable",
        print_conv: PrintConvId::NikonNEFLinearizationTable,
    },
    NIKONTag {
        id: 0x0099,
        name: "RawImageCenter",
        print_conv: PrintConvId::NikonRawImageCenter,
    },
    NIKONTag {
        id: 0x009a,
        name: "SensorPixelSize",
        print_conv: PrintConvId::NikonSensorPixelSize,
    },
    NIKONTag {
        id: 0x009c,
        name: "SceneAssist",
        print_conv: PrintConvId::NikonSceneMode,
    },
    NIKONTag {
        id: 0x009d,
        name: "DateStampMode",
        print_conv: PrintConvId::NikonDateStampMode,
    },
    NIKONTag {
        id: 0x009e,
        name: "RetouchHistory",
        print_conv: PrintConvId::NikonRetouchHistory,
    },
    NIKONTag {
        id: 0x00a0,
        name: "SerialNumber",
        print_conv: PrintConvId::NikonSerialNumber,
    },
    NIKONTag {
        id: 0x00a2,
        name: "ImageDataSize",
        print_conv: PrintConvId::NikonImageDataSize,
    },
    NIKONTag {
        id: 0x00a5,
        name: "ImageCount",
        print_conv: PrintConvId::NikonImageCount,
    },
    NIKONTag {
        id: 0x00a6,
        name: "DeletedImageCount",
        print_conv: PrintConvId::NikonDeletedImageCount,
    },
    NIKONTag {
        id: 0x00a7,
        name: "ShutterCount",
        print_conv: PrintConvId::NikonShutterCount,
    },
    NIKONTag {
        id: 0x00a9,
        name: "ImageOptimization",
        print_conv: PrintConvId::NikonImageOptimization,
    },
    NIKONTag {
        id: 0x00aa,
        name: "Saturation",
        print_conv: PrintConvId::NikonSaturation,
    },
    NIKONTag {
        id: 0x00ab,
        name: "VariProgram",
        print_conv: PrintConvId::NikonVariProgram,
    },
    NIKONTag {
        id: 0x00ac,
        name: "ImageStabilization",
        print_conv: PrintConvId::NikonImageStabilization,
    },
    NIKONTag {
        id: 0x00ad,
        name: "AFResponse",
        print_conv: PrintConvId::NikonAFResponse,
    },
    NIKONTag {
        id: 0x00b1,
        name: "HighISONoiseReduction",
        print_conv: PrintConvId::NikonHighISONoiseReduction,
    },
    NIKONTag {
        id: 0x00b3,
        name: "ToningEffect",
        print_conv: PrintConvId::NikonToningEffect,
    },
    NIKONTag {
        id: 0x00b6,
        name: "PowerUpTime",
        print_conv: PrintConvId::NikonPowerUpTime,
    },
    NIKONTag {
        id: 0x00b9,
        name: "AFTune",
        print_conv: PrintConvId::NikonAFTune,
    },
    NIKONTag {
        id: 0x00bb,
        name: "RetouchInfo",
        print_conv: PrintConvId::NikonRetouchInfo,
    },
    NIKONTag {
        id: 0x00bd,
        name: "PictureControlData",
        print_conv: PrintConvId::NikonPictureControlData,
    },
    NIKONTag {
        id: 0x00bf,
        name: "SilentPhotography",
        print_conv: PrintConvId::OnOff,
    },
    NIKONTag {
        id: 0x00c3,
        name: "BarometerInfo",
        print_conv: PrintConvId::NikonBarometerInfo,
    },
    NIKONTag {
        id: 0x0e00,
        name: "PrintIM",
        print_conv: PrintConvId::NikonPrintIM,
    },
    NIKONTag {
        id: 0x0e01,
        name: "NikonCaptureData",
        print_conv: PrintConvId::NikonNikonCaptureData,
    },
    NIKONTag {
        id: 0x0e09,
        name: "NikonCaptureVersion",
        print_conv: PrintConvId::NikonNikonCaptureVersion,
    },
    NIKONTag {
        id: 0x0e0e,
        name: "NikonCaptureOffsets",
        print_conv: PrintConvId::NikonNikonCaptureOffsets,
    },
    NIKONTag {
        id: 0x0e10,
        name: "NikonScanIFD",
        print_conv: PrintConvId::NikonNikonScanIFD,
    },
    NIKONTag {
        id: 0x0e1d,
        name: "NikonICCProfile",
        print_conv: PrintConvId::NikonNikonICCProfile,
    },
    NIKONTag {
        id: 0x0e1e,
        name: "NikonCaptureOutput",
        print_conv: PrintConvId::NikonNikonCaptureOutput,
    },
    NIKONTag {
        id: 0x0e22,
        name: "NEFBitDepth",
        print_conv: PrintConvId::NikonNEFBitDepth,
    },
];

/// Get nikon tag by ID
pub fn get_nikon_tag(tag_id: u16) -> Option<&'static NIKONTag> {
    NIKON_TAGS.iter().find(|tag| tag.id == tag_id)
}
