//! Auto-generated panasonic tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/Panasonic.pm
//! EXIFTOOL-VERSION: 12.65
//!
//! This file is auto-generated by exiftool_sync extract printconv-tables.
//! Do not edit manually.

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Panasonic.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)] // Allow ExifTool-style naming
pub struct PANASONICTag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// Panasonic tag definitions with PrintConv mappings
pub const PANASONIC_TAGS: &[PANASONICTag] = &[
    PANASONICTag {
        id: 0x0001,
        name: "ImageQuality",
        print_conv: PrintConvId::Quality,
    },
    PANASONICTag {
        id: 0x0002,
        name: "FirmwareVersion",
        print_conv: PrintConvId::PanasonicFirmwareVersion,
    },
    PANASONICTag {
        id: 0x0003,
        name: "WhiteBalance",
        print_conv: PrintConvId::WhiteBalance,
    },
    PANASONICTag {
        id: 0x0007,
        name: "FocusMode",
        print_conv: PrintConvId::PanasonicFocusMode,
    },
    PANASONICTag {
        id: 0x001a,
        name: "ImageStabilization",
        print_conv: PrintConvId::PanasonicImageStabilization,
    },
    PANASONICTag {
        id: 0x001c,
        name: "MacroMode",
        print_conv: PrintConvId::PanasonicMacroMode,
    },
    PANASONICTag {
        id: 0x001f,
        name: "ShootingMode",
        print_conv: PrintConvId::PanasonicShootingMode,
    },
    PANASONICTag {
        id: 0x0020,
        name: "Audio",
        print_conv: PrintConvId::PanasonicAudio,
    },
    PANASONICTag {
        id: 0x0021,
        name: "DataDump",
        print_conv: PrintConvId::PanasonicDataDump,
    },
    PANASONICTag {
        id: 0x0023,
        name: "WhiteBalanceBias",
        print_conv: PrintConvId::WhiteBalance,
    },
    PANASONICTag {
        id: 0x0024,
        name: "FlashBias",
        print_conv: PrintConvId::PanasonicFlashBias,
    },
    PANASONICTag {
        id: 0x0025,
        name: "InternalSerialNumber",
        print_conv: PrintConvId::PanasonicInternalSerialNumber,
    },
    PANASONICTag {
        id: 0x0026,
        name: "PanasonicExifVersion",
        print_conv: PrintConvId::PanasonicPanasonicExifVersion,
    },
    PANASONICTag {
        id: 0x0027,
        name: "VideoFrameRate",
        print_conv: PrintConvId::PanasonicVideoFrameRate,
    },
    PANASONICTag {
        id: 0x0028,
        name: "ColorEffect",
        print_conv: PrintConvId::PanasonicColorEffect,
    },
    PANASONICTag {
        id: 0x0029,
        name: "TimeSincePowerOn",
        print_conv: PrintConvId::PanasonicTimeSincePowerOn,
    },
    PANASONICTag {
        id: 0x002a,
        name: "BurstMode",
        print_conv: PrintConvId::OnOff,
    },
    PANASONICTag {
        id: 0x002b,
        name: "SequenceNumber",
        print_conv: PrintConvId::PanasonicSequenceNumber,
    },
    PANASONICTag {
        id: 0x002d,
        name: "NoiseReduction",
        print_conv: PrintConvId::PanasonicNoiseReduction,
    },
    PANASONICTag {
        id: 0x002e,
        name: "SelfTimer",
        print_conv: PrintConvId::PanasonicSelfTimer,
    },
    PANASONICTag {
        id: 0x0030,
        name: "Rotation",
        print_conv: PrintConvId::PanasonicRotation,
    },
    PANASONICTag {
        id: 0x0031,
        name: "AFAssistLamp",
        print_conv: PrintConvId::PanasonicAFAssistLamp,
    },
    PANASONICTag {
        id: 0x0032,
        name: "ColorMode",
        print_conv: PrintConvId::PanasonicColorMode,
    },
    PANASONICTag {
        id: 0x0033,
        name: "BabyAge",
        print_conv: PrintConvId::PanasonicBabyAge,
    },
    PANASONICTag {
        id: 0x0034,
        name: "OpticalZoomMode",
        print_conv: PrintConvId::PanasonicOpticalZoomMode,
    },
    PANASONICTag {
        id: 0x0035,
        name: "ConversionLens",
        print_conv: PrintConvId::PanasonicLensType,
    },
    PANASONICTag {
        id: 0x0036,
        name: "TravelDay",
        print_conv: PrintConvId::PanasonicTravelDay,
    },
    PANASONICTag {
        id: 0x0038,
        name: "BatteryLevel",
        print_conv: PrintConvId::PanasonicBatteryLevel,
    },
    PANASONICTag {
        id: 0x0039,
        name: "Contrast",
        print_conv: PrintConvId::PanasonicContrast,
    },
    PANASONICTag {
        id: 0x003a,
        name: "WorldTimeLocation",
        print_conv: PrintConvId::PanasonicWorldTimeLocation,
    },
    PANASONICTag {
        id: 0x003b,
        name: "TextStamp",
        print_conv: PrintConvId::PanasonicTextStamp,
    },
    PANASONICTag {
        id: 0x003c,
        name: "ProgramISO",
        print_conv: PrintConvId::PanasonicProgramISO,
    },
    PANASONICTag {
        id: 0x003d,
        name: "AdvancedSceneType",
        print_conv: PrintConvId::PanasonicSceneMode,
    },
    PANASONICTag {
        id: 0x003e,
        name: "TextStamp",
        print_conv: PrintConvId::PanasonicTextStamp,
    },
    PANASONICTag {
        id: 0x003f,
        name: "FacesDetected",
        print_conv: PrintConvId::PanasonicFacesDetected,
    },
    PANASONICTag {
        id: 0x0040,
        name: "Saturation",
        print_conv: PrintConvId::PanasonicSaturation,
    },
    PANASONICTag {
        id: 0x0041,
        name: "Sharpness",
        print_conv: PrintConvId::PanasonicSharpness,
    },
    PANASONICTag {
        id: 0x0042,
        name: "FilmMode",
        print_conv: PrintConvId::PanasonicFilmMode,
    },
    PANASONICTag {
        id: 0x0043,
        name: "JPEGQuality",
        print_conv: PrintConvId::Quality,
    },
    PANASONICTag {
        id: 0x0044,
        name: "ColorTempKelvin",
        print_conv: PrintConvId::PanasonicColorTempKelvin,
    },
    PANASONICTag {
        id: 0x0045,
        name: "BracketSettings",
        print_conv: PrintConvId::PanasonicBracketSettings,
    },
    PANASONICTag {
        id: 0x0046,
        name: "WBShiftAB",
        print_conv: PrintConvId::PanasonicWBShiftAB,
    },
    PANASONICTag {
        id: 0x0047,
        name: "WBShiftGM",
        print_conv: PrintConvId::PanasonicWBShiftGM,
    },
    PANASONICTag {
        id: 0x0048,
        name: "FlashCurtain",
        print_conv: PrintConvId::PanasonicFlashCurtain,
    },
    PANASONICTag {
        id: 0x0049,
        name: "LongExposureNoiseReduction",
        print_conv: PrintConvId::PanasonicLongExposureNoiseReduction,
    },
    PANASONICTag {
        id: 0x004b,
        name: "PanasonicImageWidth",
        print_conv: PrintConvId::PanasonicPanasonicImageWidth,
    },
    PANASONICTag {
        id: 0x004c,
        name: "PanasonicImageHeight",
        print_conv: PrintConvId::PanasonicPanasonicImageHeight,
    },
    PANASONICTag {
        id: 0x004d,
        name: "AFPointPosition",
        print_conv: PrintConvId::PanasonicAFPointPosition,
    },
    PANASONICTag {
        id: 0x004e,
        name: "FaceDetInfo",
        print_conv: PrintConvId::PanasonicFaceDetInfo,
    },
    PANASONICTag {
        id: 0x0051,
        name: "LensType",
        print_conv: PrintConvId::PanasonicLensType,
    },
    PANASONICTag {
        id: 0x0052,
        name: "LensSerialNumber",
        print_conv: PrintConvId::PanasonicLensType,
    },
    PANASONICTag {
        id: 0x0053,
        name: "AccessoryType",
        print_conv: PrintConvId::PanasonicAccessoryType,
    },
    PANASONICTag {
        id: 0x0054,
        name: "AccessorySerialNumber",
        print_conv: PrintConvId::PanasonicAccessorySerialNumber,
    },
    PANASONICTag {
        id: 0x0059,
        name: "Transform",
        print_conv: PrintConvId::PanasonicTransform,
    },
    PANASONICTag {
        id: 0x005d,
        name: "IntelligentExposure",
        print_conv: PrintConvId::PanasonicIntelligentExposure,
    },
    PANASONICTag {
        id: 0x0060,
        name: "LensFirmwareVersion",
        print_conv: PrintConvId::PanasonicLensType,
    },
    PANASONICTag {
        id: 0x0061,
        name: "FaceRecInfo",
        print_conv: PrintConvId::PanasonicFaceRecInfo,
    },
    PANASONICTag {
        id: 0x0062,
        name: "FlashWarning",
        print_conv: PrintConvId::PanasonicFlashWarning,
    },
    PANASONICTag {
        id: 0x0063,
        name: "RecognizedFaceFlags",
        print_conv: PrintConvId::PanasonicRecognizedFaceFlags,
    },
    PANASONICTag {
        id: 0x0065,
        name: "Title",
        print_conv: PrintConvId::PanasonicTitle,
    },
    PANASONICTag {
        id: 0x0066,
        name: "BabyName",
        print_conv: PrintConvId::PanasonicBabyName,
    },
    PANASONICTag {
        id: 0x0067,
        name: "Location",
        print_conv: PrintConvId::PanasonicLocation,
    },
    PANASONICTag {
        id: 0x0069,
        name: "Country",
        print_conv: PrintConvId::PanasonicCountry,
    },
    PANASONICTag {
        id: 0x006b,
        name: "State",
        print_conv: PrintConvId::PanasonicState,
    },
    PANASONICTag {
        id: 0x006d,
        name: "City",
        print_conv: PrintConvId::PanasonicCity,
    },
    PANASONICTag {
        id: 0x006f,
        name: "Landmark",
        print_conv: PrintConvId::PanasonicLandmark,
    },
    PANASONICTag {
        id: 0x0070,
        name: "IntelligentResolution",
        print_conv: PrintConvId::PanasonicIntelligentResolution,
    },
    PANASONICTag {
        id: 0x0076,
        name: "MergedImages",
        print_conv: PrintConvId::PanasonicMergedImages,
    },
    PANASONICTag {
        id: 0x0077,
        name: "BurstSpeed",
        print_conv: PrintConvId::PanasonicBurstSpeed,
    },
    PANASONICTag {
        id: 0x0079,
        name: "IntelligentD-Range",
        print_conv: PrintConvId::PanasonicIntelligentD_Range,
    },
    PANASONICTag {
        id: 0x007c,
        name: "ClearRetouch",
        print_conv: PrintConvId::OnOff,
    },
    PANASONICTag {
        id: 0x0080,
        name: "City2",
        print_conv: PrintConvId::PanasonicCity2,
    },
    PANASONICTag {
        id: 0x0086,
        name: "ManometerPressure",
        print_conv: PrintConvId::PanasonicManometerPressure,
    },
    PANASONICTag {
        id: 0x0089,
        name: "PhotoStyle",
        print_conv: PrintConvId::PanasonicPhotoStyle,
    },
    PANASONICTag {
        id: 0x008a,
        name: "ShadingCompensation",
        print_conv: PrintConvId::OnOff,
    },
    PANASONICTag {
        id: 0x008b,
        name: "WBShiftIntelligentAuto",
        print_conv: PrintConvId::PanasonicWBShiftIntelligentAuto,
    },
    PANASONICTag {
        id: 0x008c,
        name: "AccelerometerZ",
        print_conv: PrintConvId::PanasonicAccelerometerZ,
    },
    PANASONICTag {
        id: 0x008d,
        name: "AccelerometerX",
        print_conv: PrintConvId::PanasonicAccelerometerX,
    },
    PANASONICTag {
        id: 0x008e,
        name: "AccelerometerY",
        print_conv: PrintConvId::PanasonicAccelerometerY,
    },
    PANASONICTag {
        id: 0x008f,
        name: "CameraOrientation",
        print_conv: PrintConvId::PanasonicCameraOrientation,
    },
    PANASONICTag {
        id: 0x0090,
        name: "RollAngle",
        print_conv: PrintConvId::PanasonicRollAngle,
    },
    PANASONICTag {
        id: 0x0091,
        name: "PitchAngle",
        print_conv: PrintConvId::PanasonicPitchAngle,
    },
    PANASONICTag {
        id: 0x0092,
        name: "WBShiftCreativeControl",
        print_conv: PrintConvId::PanasonicWBShiftCreativeControl,
    },
    PANASONICTag {
        id: 0x0093,
        name: "SweepPanoramaDirection",
        print_conv: PrintConvId::PanasonicSweepPanoramaDirection,
    },
    PANASONICTag {
        id: 0x0094,
        name: "SweepPanoramaFieldOfView",
        print_conv: PrintConvId::PanasonicSweepPanoramaFieldOfView,
    },
    PANASONICTag {
        id: 0x0096,
        name: "TimerRecording",
        print_conv: PrintConvId::PanasonicTimerRecording,
    },
    PANASONICTag {
        id: 0x009d,
        name: "InternalNDFilter",
        print_conv: PrintConvId::PanasonicInternalNDFilter,
    },
    PANASONICTag {
        id: 0x009e,
        name: "HDR",
        print_conv: PrintConvId::PanasonicHDR,
    },
    PANASONICTag {
        id: 0x009f,
        name: "ShutterType",
        print_conv: PrintConvId::PanasonicShutterType,
    },
    PANASONICTag {
        id: 0x00a1,
        name: "FilterEffect",
        print_conv: PrintConvId::PanasonicFilterEffect,
    },
    PANASONICTag {
        id: 0x00a3,
        name: "ClearRetouchValue",
        print_conv: PrintConvId::PanasonicClearRetouchValue,
    },
    PANASONICTag {
        id: 0x00a7,
        name: "OutputLUT",
        print_conv: PrintConvId::PanasonicOutputLUT,
    },
    PANASONICTag {
        id: 0x00ab,
        name: "TouchAE",
        print_conv: PrintConvId::OnOff,
    },
    PANASONICTag {
        id: 0x00ac,
        name: "MonochromeFilterEffect",
        print_conv: PrintConvId::PanasonicMonochromeFilterEffect,
    },
    PANASONICTag {
        id: 0x00ad,
        name: "HighlightShadow",
        print_conv: PrintConvId::PanasonicHighlightShadow,
    },
    PANASONICTag {
        id: 0x00af,
        name: "TimeStamp",
        print_conv: PrintConvId::PanasonicTimeStamp,
    },
    PANASONICTag {
        id: 0x00b3,
        name: "VideoBurstResolution",
        print_conv: PrintConvId::PanasonicVideoBurstResolution,
    },
    PANASONICTag {
        id: 0x00b4,
        name: "MultiExposure",
        print_conv: PrintConvId::PanasonicMultiExposure,
    },
    PANASONICTag {
        id: 0x00b9,
        name: "RedEyeRemoval",
        print_conv: PrintConvId::OnOff,
    },
    PANASONICTag {
        id: 0x00bb,
        name: "VideoBurstMode",
        print_conv: PrintConvId::PanasonicVideoBurstMode,
    },
    PANASONICTag {
        id: 0x00bc,
        name: "DiffractionCorrection",
        print_conv: PrintConvId::PanasonicDiffractionCorrection,
    },
    PANASONICTag {
        id: 0x00bd,
        name: "FocusBracket",
        print_conv: PrintConvId::PanasonicFocusBracket,
    },
    PANASONICTag {
        id: 0x00be,
        name: "LongExposureNRUsed",
        print_conv: PrintConvId::YesNo,
    },
    PANASONICTag {
        id: 0x00bf,
        name: "PostFocusMerging",
        print_conv: PrintConvId::PanasonicPostFocusMerging,
    },
    PANASONICTag {
        id: 0x00c1,
        name: "VideoPreburst",
        print_conv: PrintConvId::PanasonicVideoPreburst,
    },
    PANASONICTag {
        id: 0x00ca,
        name: "SensorType",
        print_conv: PrintConvId::PanasonicSensorType,
    },
    PANASONICTag {
        id: 0x00c4,
        name: "LensTypeMake",
        print_conv: PrintConvId::PanasonicLensType,
    },
    PANASONICTag {
        id: 0x00c5,
        name: "LensTypeModel",
        print_conv: PrintConvId::PanasonicModelLookup,
    },
    PANASONICTag {
        id: 0x00d1,
        name: "ISO",
        print_conv: PrintConvId::PanasonicISO,
    },
    PANASONICTag {
        id: 0x00d2,
        name: "MonochromeGrainEffect",
        print_conv: PrintConvId::PanasonicMonochromeGrainEffect,
    },
    PANASONICTag {
        id: 0x00d6,
        name: "NoiseReductionStrength",
        print_conv: PrintConvId::PanasonicNoiseReductionStrength,
    },
    PANASONICTag {
        id: 0x00e4,
        name: "LensTypeModel",
        print_conv: PrintConvId::PanasonicModelLookup,
    },
    PANASONICTag {
        id: 0x00e8,
        name: "MinimumISO",
        print_conv: PrintConvId::PanasonicMinimumISO,
    },
    PANASONICTag {
        id: 0x00e9,
        name: "AFSubjectDetection",
        print_conv: PrintConvId::PanasonicAFSubjectDetection,
    },
    PANASONICTag {
        id: 0x00ee,
        name: "DynamicRangeBoost",
        print_conv: PrintConvId::OnOff,
    },
    PANASONICTag {
        id: 0x0e00,
        name: "PrintIM",
        print_conv: PrintConvId::PanasonicPrintIM,
    },
    PANASONICTag {
        id: 0x2003,
        name: "TimeInfo",
        print_conv: PrintConvId::PanasonicTimeInfo,
    },
    PANASONICTag {
        id: 0x8000,
        name: "MakerNoteVersion",
        print_conv: PrintConvId::PanasonicMakerNoteVersion,
    },
    PANASONICTag {
        id: 0x8001,
        name: "SceneMode",
        print_conv: PrintConvId::PanasonicSceneMode,
    },
    PANASONICTag {
        id: 0x8002,
        name: "HighlightWarning",
        print_conv: PrintConvId::PanasonicHighlightWarning,
    },
    PANASONICTag {
        id: 0x8003,
        name: "DarkFocusEnvironment",
        print_conv: PrintConvId::PanasonicDarkFocusEnvironment,
    },
    PANASONICTag {
        id: 0x8004,
        name: "WBRedLevel",
        print_conv: PrintConvId::PanasonicWBRedLevel,
    },
    PANASONICTag {
        id: 0x8005,
        name: "WBGreenLevel",
        print_conv: PrintConvId::PanasonicWBGreenLevel,
    },
    PANASONICTag {
        id: 0x8006,
        name: "WBBlueLevel",
        print_conv: PrintConvId::PanasonicWBBlueLevel,
    },
    PANASONICTag {
        id: 0x8007,
        name: "FlashFired",
        print_conv: PrintConvId::PanasonicFlashFired,
    },
    PANASONICTag {
        id: 0x8008,
        name: "TextStamp",
        print_conv: PrintConvId::PanasonicTextStamp,
    },
    PANASONICTag {
        id: 0x8009,
        name: "TextStamp",
        print_conv: PrintConvId::PanasonicTextStamp,
    },
    PANASONICTag {
        id: 0x8010,
        name: "BabyAge",
        print_conv: PrintConvId::PanasonicBabyAge,
    },
    PANASONICTag {
        id: 0x8012,
        name: "Transform",
        print_conv: PrintConvId::PanasonicTransform,
    },
];

/// Get panasonic tag by ID
pub fn get_panasonic_tag(tag_id: u16) -> Option<&'static PANASONICTag> {
    PANASONIC_TAGS.iter().find(|tag| tag.id == tag_id)
}
