//! Auto-generated sony tag table with PrintConv mappings
//!
//! EXIFTOOL-SOURCE: lib/Image/ExifTool/Sony.pm
//! EXIFTOOL-VERSION: 12.65
//!
//! This file is auto-generated by exiftool_sync extract printconv-tables.
//! Do not edit manually.

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Sony.pm"]

use crate::core::print_conv::PrintConvId;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)]  // Allow ExifTool-style naming
pub struct SONYTag {
    pub id: u16,
    pub name: &'static str,
    pub print_conv: PrintConvId,
}

/// Sony tag definitions with PrintConv mappings
pub const SONY_TAGS: &[SONYTag] = &[
    SONYTag { id: 0x0102, name: "Quality", print_conv: PrintConvId::Quality },
    SONYTag { id: 0x0104, name: "FlashExposureComp", print_conv: PrintConvId::SonyFlashExposureComp },
    SONYTag { id: 0x0105, name: "Teleconverter", print_conv: PrintConvId::SonyImage },
    SONYTag { id: 0x0112, name: "WhiteBalanceFineTune", print_conv: PrintConvId::WhiteBalance },
    SONYTag { id: 0x0115, name: "WhiteBalance", print_conv: PrintConvId::WhiteBalance },
    SONYTag { id: 0x0e00, name: "PrintIM", print_conv: PrintConvId::SonyPrintIM },
    SONYTag { id: 0x1000, name: "MultiBurstMode", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0x1001, name: "MultiBurstImageWidth", print_conv: PrintConvId::SonyMultiBurstImageWidth },
    SONYTag { id: 0x1002, name: "MultiBurstImageHeight", print_conv: PrintConvId::SonyMultiBurstImageHeight },
    SONYTag { id: 0x1003, name: "Panorama", print_conv: PrintConvId::SonyPanorama },
    SONYTag { id: 0x2001, name: "PreviewImage", print_conv: PrintConvId::SonyPreviewImage },
    SONYTag { id: 0x2002, name: "Rating", print_conv: PrintConvId::SonyRating },
    SONYTag { id: 0x2004, name: "Contrast", print_conv: PrintConvId::SonyContrast },
    SONYTag { id: 0x2005, name: "Saturation", print_conv: PrintConvId::SonySaturation },
    SONYTag { id: 0x2006, name: "Sharpness", print_conv: PrintConvId::SonySharpness },
    SONYTag { id: 0x2007, name: "Brightness", print_conv: PrintConvId::SonyBrightness },
    SONYTag { id: 0x2008, name: "LongExposureNoiseReduction", print_conv: PrintConvId::SonyLongExposureNoiseReduction },
    SONYTag { id: 0x2009, name: "HighISONoiseReduction", print_conv: PrintConvId::SonyHighISONoiseReduction },
    SONYTag { id: 0x200a, name: "HDR", print_conv: PrintConvId::SonyHDR },
    SONYTag { id: 0x200b, name: "MultiFrameNoiseReduction", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0x200e, name: "PictureEffect", print_conv: PrintConvId::SonyPictureEffect },
    SONYTag { id: 0x200f, name: "SoftSkinEffect", print_conv: PrintConvId::SonySoftSkinEffect },
    SONYTag { id: 0x2011, name: "VignettingCorrection", print_conv: PrintConvId::SonyVignettingCorrection },
    SONYTag { id: 0x2012, name: "LateralChromaticAberration", print_conv: PrintConvId::SonyLateralChromaticAberration },
    SONYTag { id: 0x2013, name: "DistortionCorrectionSetting", print_conv: PrintConvId::SonyDistortionCorrectionSetting },
    SONYTag { id: 0x2014, name: "WBShiftAB_GM", print_conv: PrintConvId::SonyWBShiftAB_GM },
    SONYTag { id: 0x2016, name: "AutoPortraitFramed", print_conv: PrintConvId::YesNo },
    SONYTag { id: 0x2017, name: "FlashAction", print_conv: PrintConvId::SonyFlashAction },
    SONYTag { id: 0x201a, name: "ElectronicFrontCurtainShutter", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0x201b, name: "FocusMode", print_conv: PrintConvId::SonyFocusMode },
    SONYTag { id: 0x201d, name: "FlexibleSpotPosition", print_conv: PrintConvId::SonyFlexibleSpotPosition },
    SONYTag { id: 0x2021, name: "AFTracking", print_conv: PrintConvId::SonyAFTracking },
    SONYTag { id: 0x2023, name: "MultiFrameNREffect", print_conv: PrintConvId::SonyMultiFrameNREffect },
    SONYTag { id: 0x2026, name: "WBShiftAB_GM_Precise", print_conv: PrintConvId::SonyWBShiftAB_GM_Precise },
    SONYTag { id: 0x2027, name: "FocusLocation", print_conv: PrintConvId::SonyFocusLocation },
    SONYTag { id: 0x2028, name: "VariableLowPassFilter", print_conv: PrintConvId::SonyVariableLowPassFilter },
    SONYTag { id: 0x2029, name: "RAWFileType", print_conv: PrintConvId::SonyRAWFileType },
    SONYTag { id: 0x202a, name: "Tag202a", print_conv: PrintConvId::SonyTag202a },
    SONYTag { id: 0x202b, name: "PrioritySetInAWB", print_conv: PrintConvId::SonyPrioritySetInAWB },
    SONYTag { id: 0x202c, name: "MeteringMode2", print_conv: PrintConvId::MeteringMode },
    SONYTag { id: 0x202d, name: "ExposureStandardAdjustment", print_conv: PrintConvId::SonyExposureStandardAdjustment },
    SONYTag { id: 0x202e, name: "Quality", print_conv: PrintConvId::Quality },
    SONYTag { id: 0x202f, name: "PixelShiftInfo", print_conv: PrintConvId::SonyPixelShiftInfo },
    SONYTag { id: 0x2031, name: "SerialNumber", print_conv: PrintConvId::SonySerialNumber },
    SONYTag { id: 0x2032, name: "Shadows", print_conv: PrintConvId::SonyShadows },
    SONYTag { id: 0x2033, name: "Highlights", print_conv: PrintConvId::SonyHighlights },
    SONYTag { id: 0x2034, name: "Fade", print_conv: PrintConvId::SonyFade },
    SONYTag { id: 0x2035, name: "SharpnessRange", print_conv: PrintConvId::SonySharpnessRange },
    SONYTag { id: 0x2036, name: "Clarity", print_conv: PrintConvId::SonyClarity },
    SONYTag { id: 0x2037, name: "FocusFrameSize", print_conv: PrintConvId::SonyFocusFrameSize },
    SONYTag { id: 0x2039, name: "JPEG-HEIFSwitch", print_conv: PrintConvId::SonyJPEG_HEIFSwitch },
    SONYTag { id: 0x2044, name: "HiddenInfo", print_conv: PrintConvId::SonyHiddenInfo },
    SONYTag { id: 0x204a, name: "FocusLocation2", print_conv: PrintConvId::SonyFocusLocation2 },
    SONYTag { id: 0x3000, name: "ShotInfo", print_conv: PrintConvId::SonyShotInfo },
    SONYTag { id: 0x900b, name: "Tag900b", print_conv: PrintConvId::SonyTag900b },
    SONYTag { id: 0x9401, name: "Tag9401", print_conv: PrintConvId::SonyTag9401 },
    SONYTag { id: 0x0007, name: "DynamicRangeOptimizer_9401", print_conv: PrintConvId::SonyDynamicRangeOptimizer_9401 },
    SONYTag { id: 0x9403, name: "Tag9403", print_conv: PrintConvId::SonyTag9403 },
    SONYTag { id: 0x9407, name: "Sony_0x9407", print_conv: PrintConvId::SonySony_0x9407 },
    SONYTag { id: 0x9408, name: "Sony_0x9408", print_conv: PrintConvId::SonySony_0x9408 },
    SONYTag { id: 0x9409, name: "Sony_0x9409", print_conv: PrintConvId::SonySony_0x9409 },
    SONYTag { id: 0x940b, name: "Sony_0x940b", print_conv: PrintConvId::SonySony_0x940b },
    SONYTag { id: 0x940d, name: "Sony_0x940d", print_conv: PrintConvId::SonySony_0x940d },
    SONYTag { id: 0x940f, name: "Sony_0x940f", print_conv: PrintConvId::SonySony_0x940f },
    SONYTag { id: 0x9411, name: "Sony_0x9411", print_conv: PrintConvId::SonySony_0x9411 },
    SONYTag { id: 0x9416, name: "Sony_0x9416", print_conv: PrintConvId::SonySony_0x9416 },
    SONYTag { id: 0xb000, name: "FileFormat", print_conv: PrintConvId::SonyFileFormat },
    SONYTag { id: 0xb001, name: "SonyModelID", print_conv: PrintConvId::SonyModelLookup },
    SONYTag { id: 0xb020, name: "CreativeStyle", print_conv: PrintConvId::SonyCreativeStyle },
    SONYTag { id: 0xb021, name: "ColorTemperature", print_conv: PrintConvId::SonyColorTemperature },
    SONYTag { id: 0xb022, name: "ColorCompensationFilter", print_conv: PrintConvId::SonyColorCompensationFilter },
    SONYTag { id: 0xb023, name: "SceneMode", print_conv: PrintConvId::SonyImage },
    SONYTag { id: 0xb024, name: "ZoneMatching", print_conv: PrintConvId::SonyZoneMatching },
    SONYTag { id: 0xb025, name: "DynamicRangeOptimizer", print_conv: PrintConvId::SonyDynamicRangeOptimizer },
    SONYTag { id: 0xb026, name: "ImageStabilization", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0xb027, name: "LensType", print_conv: PrintConvId::SonySonyLensTypes },
    SONYTag { id: 0xb028, name: "MinoltaMakerNote", print_conv: PrintConvId::SonyMinoltaMakerNote },
    SONYTag { id: 0xb029, name: "ColorMode", print_conv: PrintConvId::SonyImage },
    SONYTag { id: 0xb02a, name: "LensSpec", print_conv: PrintConvId::SonyLensType },
    SONYTag { id: 0xb02b, name: "FullImageSize", print_conv: PrintConvId::SonyFullImageSize },
    SONYTag { id: 0xb02c, name: "PreviewImageSize", print_conv: PrintConvId::SonyPreviewImageSize },
    SONYTag { id: 0xb040, name: "Macro", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0xb041, name: "ExposureMode", print_conv: PrintConvId::SonyExposureMode },
    SONYTag { id: 0xb042, name: "FocusMode", print_conv: PrintConvId::SonyFocusMode },
    SONYTag { id: 0xb044, name: "AFIlluminator", print_conv: PrintConvId::SonyAFIlluminator },
    SONYTag { id: 0xb047, name: "JPEGQuality", print_conv: PrintConvId::Quality },
    SONYTag { id: 0xb048, name: "FlashLevel", print_conv: PrintConvId::SonyFlashLevel },
    SONYTag { id: 0xb049, name: "ReleaseMode", print_conv: PrintConvId::SonyReleaseMode },
    SONYTag { id: 0xb04a, name: "SequenceNumber", print_conv: PrintConvId::SonySequenceNumber },
    SONYTag { id: 0xb04b, name: "Anti-Blur", print_conv: PrintConvId::SonyAnti_Blur },
    SONYTag { id: 0xb04e, name: "LongExposureNoiseReduction", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0xb04e, name: "FocusMode", print_conv: PrintConvId::SonyFocusMode },
    SONYTag { id: 0xb04f, name: "DynamicRangeOptimizer", print_conv: PrintConvId::SonyDynamicRangeOptimizer },
    SONYTag { id: 0xb050, name: "HighISONoiseReduction2", print_conv: PrintConvId::SonyHighISONoiseReduction2 },
    SONYTag { id: 0xb052, name: "IntelligentAuto", print_conv: PrintConvId::OnOff },
    SONYTag { id: 0xb054, name: "WhiteBalance", print_conv: PrintConvId::WhiteBalance },
];

/// Get sony tag by ID
pub fn get_sony_tag(tag_id: u16) -> Option<&'static SONYTag> {
    SONY_TAGS.iter().find(|tag| tag.id == tag_id)
}
