// AUTO-GENERATED by exiftool_sync extract binary-formats
// Source: third-party/exiftool/lib/Image/ExifTool/Nikon.pm
// Generated by exiftool_sync extract binary-formats
// DO NOT EDIT - Regenerate with `cargo run --bin exiftool_sync extract binary-formats`

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Nikon.pm"]

use crate::core::binary_data::{BinaryDataTable, BinaryDataTableBuilder};
use crate::core::types::ExifFormat;

/// Binary data table: ROC
/// Source lines: 3334-3343
/// Process function: ProcessBinaryData
pub fn create_roc_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ROC", ExifFormat::U32)
        .add_field(0, "DigitalROC", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: GEM
/// Source lines: 3346-3355
/// Process function: ProcessBinaryData
pub fn create_gem_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("GEM", ExifFormat::U32)
        .add_field(0, "DigitalGEM", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: FaceDetect
/// Source lines: 3404-3482
/// Process function: ProcessBinaryData
pub fn create_facedetect_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("FaceDetect", ExifFormat::U16)
        .add_field(1, "FaceDetectFrameSize", ExifFormat::U16, 2)
        .add_field(3, "FacesDetected", ExifFormat::U16, 1)
        .add_field(8, "Face2Position", ExifFormat::U16, 4)
        .add_field(12, "Face3Position", ExifFormat::U16, 4)
        .add_field(16, "Face4Position", ExifFormat::U16, 4)
        .add_field(20, "Face5Position", ExifFormat::U16, 4)
        .add_field(24, "Face6Position", ExifFormat::U16, 4)
        .add_field(28, "Face7Position", ExifFormat::U16, 4)
        .add_field(32, "Face8Position", ExifFormat::U16, 4)
        .add_field(36, "Face9Position", ExifFormat::U16, 4)
        .add_field(40, "Face10Position", ExifFormat::U16, 4)
        .add_field(44, "Face11Position", ExifFormat::U16, 4)
        .add_field(48, "Face12Position", ExifFormat::U16, 4)
        .build()
}

/// Binary data table: DistortInfo
/// Source lines: 4039-4057
/// Process function: ProcessBinaryData
pub fn create_distortinfo_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("DistortInfo", ExifFormat::U8)
        .add_field(0, "DistortionVersion", ExifFormat::Undefined, 4)
        .build()
}

/// Binary data table: UnknownInfo
/// Source lines: 4060-4072
/// Process function: ProcessBinaryData
pub fn create_unknowninfo_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("UnknownInfo", ExifFormat::U32)
        .add_field(0, "UnknownInfoVersion", ExifFormat::Undefined, 4)
        // Condition: $$valPt =~ /^\d{4}/
        .build()
}

/// Binary data table: UnknownInfo2
/// Source lines: 4075-4087
/// Process function: ProcessBinaryData
pub fn create_unknowninfo2_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("UnknownInfo2", ExifFormat::U32)
        .add_field(0, "UnknownInfo2Version", ExifFormat::Undefined, 4)
        // Condition: $$valPt =~ /^\d{4}/
        .build()
}

/// Binary data table: RetouchInfo
/// Source lines: 5101-5121
/// Process function: ProcessBinaryData
pub fn create_retouchinfo_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("RetouchInfo", ExifFormat::U8)
        .add_field(0, "RetouchInfoVersion", ExifFormat::Undefined, 4)
        .build()
}

/// Binary data table: FileInfo
/// Source lines: 5124-5144
/// Process function: ProcessBinaryData
pub fn create_fileinfo_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("FileInfo", ExifFormat::U16)
        .add_field(0, "FileInfoVersion", ExifFormat::Undefined, 4)
        .add_field(2, "MemoryCardNumber", ExifFormat::U16, 1)
        .add_field(3, "DirectoryNumber", ExifFormat::U16, 1)
        .add_field(4, "FileNumber", ExifFormat::U16, 1)
        .build()
}

/// Binary data table: BarometerInfo
/// Source lines: 5147-5162
/// Process function: ProcessBinaryData
pub fn create_barometerinfo_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("BarometerInfo", ExifFormat::U8)
        .add_field(0, "BarometerInfoVersion", ExifFormat::Undefined, 4)
        .add_field(6, "Altitude", ExifFormat::I32, 1)
        .build()
}

/// Binary data table: CaptureOffsets
/// Source lines: 5165-5173
/// Process function: ProcessNikonCaptureOffsets
pub fn create_captureoffsets_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("CaptureOffsets", ExifFormat::U8)
        .add_field(1, "IFD0_Offset", ExifFormat::U8, 1)
        .add_field(2, "PreviewIFD_Offset", ExifFormat::U8, 1)
        .add_field(3, "SubIFD_Offset", ExifFormat::U8, 1)
        .build()
}

/// Binary data table: CaptureOutput
/// Source lines: 5176-5185
/// Process function: ProcessBinaryData
pub fn create_captureoutput_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("CaptureOutput", ExifFormat::U32)
        .add_field(2, "OutputImageWidth", ExifFormat::U32, 1)
        .add_field(3, "OutputImageHeight", ExifFormat::U32, 1)
        .add_field(4, "OutputResolution", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ColorBalanceA
/// Source lines: 5188-5237
/// Process function: ProcessBinaryData
pub fn create_colorbalancea_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalanceA", ExifFormat::U16)
        .add_field(624, "WB_RBLevels", ExifFormat::U16, 2)
        .add_field(626, "WB_RBLevelsAuto", ExifFormat::U16, 2)
        .add_field(628, "WB_RBLevelsDaylight", ExifFormat::U16, 14)
        .add_field(642, "WB_RBLevelsIncandescent", ExifFormat::U16, 14)
        .add_field(656, "WB_RBLevelsFluorescent", ExifFormat::U16, 6)
        .add_field(662, "WB_RBLevelsCloudy", ExifFormat::U16, 14)
        .add_field(676, "WB_RBLevelsFlash", ExifFormat::U16, 14)
        .add_field(690, "WB_RBLevelsShade", ExifFormat::U16, 14)
        // Condition: $$self{Model} ne "E8700"
        .build()
}

/// Binary data table: ColorBalance1
/// Source lines: 5296-5305
/// Process function: ProcessBinaryData
pub fn create_colorbalance1_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalance1", ExifFormat::U16)
        .add_field(0, "WB_RBGGLevels", ExifFormat::U16, 4)
        .build()
}

/// Binary data table: ColorBalance2
/// Source lines: 5308-5318
/// Process function: ProcessBinaryData
pub fn create_colorbalance2_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalance2", ExifFormat::U16)
        .add_field(0, "WB_RGGBLevels", ExifFormat::U16, 4)
        .build()
}

/// Binary data table: ColorBalance3
/// Source lines: 5321-5330
/// Process function: ProcessBinaryData
pub fn create_colorbalance3_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalance3", ExifFormat::U16)
        .add_field(0, "WB_RGBGLevels", ExifFormat::U16, 4)
        .build()
}

/// Binary data table: ColorBalance4
/// Source lines: 5333-5342
/// Process function: ProcessBinaryData
pub fn create_colorbalance4_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalance4", ExifFormat::U16)
        .add_field(0, "WB_GRBGLevels", ExifFormat::U16, 4)
        .build()
}

/// Binary data table: ColorBalanceUnknown
/// Source lines: 5344-5351
/// Process function: ProcessBinaryData
pub fn create_colorbalanceunknown_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalanceUnknown", ExifFormat::U8)
        .add_field(0, "ColorBalanceVersion", ExifFormat::Undefined, 4)
        .build()
}

/// Binary data table: ColorBalanceUnknown2
/// Source lines: 5353-5361
/// Process function: ProcessBinaryData
pub fn create_colorbalanceunknown2_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ColorBalanceUnknown2", ExifFormat::U16)
        .add_field(0, "ColorBalanceVersion", ExifFormat::Undefined, 4)
        .build()
}

/// Binary data table: LensDataUnknown
/// Source lines: 5956-5964
/// Process function: ProcessBinaryData
pub fn create_lensdataunknown_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("LensDataUnknown", ExifFormat::U8)
        .add_field(0, "LensDataVersion", ExifFormat::Ascii, 4)
        .build()
}

/// Binary data table: ShotInfoD40
/// Source lines: 6084-6116
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod40_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD40", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(582, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD80
/// Source lines: 6119-6195
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod80_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD80", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(586, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD90
/// Source lines: 6198-6240
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod90_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD90", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(693, "ISO2", ExifFormat::U8, 1)
        .add_field(725, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD3a
/// Source lines: 6243-6303
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod3a_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD3a", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(598, "ISO2", ExifFormat::U8, 1)
        .add_field(630, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD3b
/// Source lines: 6306-6397
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod3b_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD3b", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(605, "ISO2", ExifFormat::U8, 1)
        .add_field(637, "ShutterCount", ExifFormat::U32, 1)
        // Condition: $$self{FirmwareVersion} =~ /^1\.01/
        .add_field(639, "ShutterCount", ExifFormat::U32, 1)
        // Condition: $$self{FirmwareVersion} =~ /^2\.0/
        .add_field(650, "PreFlashReturnStrength", ExifFormat::U8, 1)
        .build()
}

/// Binary data table: ShotInfoD3X
/// Source lines: 6400-6442
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod3x_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD3X", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(605, "ISO2", ExifFormat::U8, 1)
        .add_field(640, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD3S
/// Source lines: 6445-6514
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod3s_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD3S", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(545, "ISO2", ExifFormat::U8, 1)
        .add_field(578, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD300a
/// Source lines: 6517-6606
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod300a_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD300a", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(604, "ISO2", ExifFormat::U8, 1)
        .add_field(633, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD300b
/// Source lines: 6609-6756
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod300b_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD300b", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(613, "ISO2", ExifFormat::U8, 1)
        .add_field(644, "ShutterCount", ExifFormat::U32, 1)
        .add_field(57406, "+20", ExifFormat::U8, 1)
        .add_field(51262, "+19", ExifFormat::U8, 1)
        .add_field(45118, "+18", ExifFormat::U8, 1)
        .add_field(38974, "+17", ExifFormat::U8, 1)
        .add_field(32830, "+16", ExifFormat::U8, 1)
        .add_field(26686, "+15", ExifFormat::U8, 1)
        .add_field(20542, "+14", ExifFormat::U8, 1)
        .add_field(14398, "+13", ExifFormat::U8, 1)
        .add_field(8254, "+12", ExifFormat::U8, 1)
        .add_field(2110, "+11", ExifFormat::U8, 1)
        .add_field(57405, "+10", ExifFormat::U8, 1)
        .add_field(45117, "+9", ExifFormat::U8, 1)
        .add_field(32829, "+8", ExifFormat::U8, 1)
        .add_field(20541, "+7", ExifFormat::U8, 1)
        .add_field(8253, "+6", ExifFormat::U8, 1)
        .add_field(57404, "+5", ExifFormat::U8, 1)
        .add_field(32828, "+4", ExifFormat::U8, 1)
        .add_field(8252, "+3", ExifFormat::U8, 1)
        .add_field(32827, "+2", ExifFormat::U8, 1)
        .add_field(32826, "+1", ExifFormat::U8, 1)
        .add_field(0, "0", ExifFormat::U8, 1)
        .add_field(32966, "-1", ExifFormat::U8, 1)
        .add_field(32965, "-2", ExifFormat::U8, 1)
        .add_field(8388, "-3", ExifFormat::U8, 1)
        .add_field(32964, "-4", ExifFormat::U8, 1)
        .add_field(57540, "-5", ExifFormat::U8, 1)
        .add_field(8387, "-6", ExifFormat::U8, 1)
        .add_field(20675, "-7", ExifFormat::U8, 1)
        .add_field(32963, "-8", ExifFormat::U8, 1)
        .add_field(45251, "-9", ExifFormat::U8, 1)
        .add_field(57539, "-10", ExifFormat::U8, 1)
        .add_field(2242, "-11", ExifFormat::U8, 1)
        .add_field(8386, "-12", ExifFormat::U8, 1)
        .add_field(14530, "-13", ExifFormat::U8, 1)
        .add_field(20674, "-14", ExifFormat::U8, 1)
        .add_field(26818, "-15", ExifFormat::U8, 1)
        .add_field(32962, "-16", ExifFormat::U8, 1)
        .add_field(39106, "-17", ExifFormat::U8, 1)
        .add_field(45250, "-18", ExifFormat::U8, 1)
        .add_field(51394, "-19", ExifFormat::U8, 1)
        .add_field(57538, "-20", ExifFormat::U8, 1)
        .add_field(36926, "+20", ExifFormat::U8, 1)
        .add_field(31806, "+19", ExifFormat::U8, 1)
        .add_field(26686, "+18", ExifFormat::U8, 1)
        .add_field(21566, "+17", ExifFormat::U8, 1)
        .add_field(16446, "+16", ExifFormat::U8, 1)
        .add_field(11326, "+15", ExifFormat::U8, 1)
        .add_field(6206, "+14", ExifFormat::U8, 1)
        .add_field(1086, "+13", ExifFormat::U8, 1)
        .add_field(57405, "+12", ExifFormat::U8, 1)
        .add_field(47165, "+11", ExifFormat::U8, 1)
        .add_field(36925, "+10", ExifFormat::U8, 1)
        .add_field(26685, "+9", ExifFormat::U8, 1)
        .add_field(16445, "+8", ExifFormat::U8, 1)
        .add_field(6205, "+7", ExifFormat::U8, 1)
        .add_field(57404, "+6", ExifFormat::U8, 1)
        .add_field(36924, "+5", ExifFormat::U8, 1)
        .add_field(16444, "+4", ExifFormat::U8, 1)
        .add_field(57403, "+3", ExifFormat::U8, 1)
        .add_field(16443, "+2", ExifFormat::U8, 1)
        .add_field(16442, "+1", ExifFormat::U8, 1)
        .add_field(0, "0", ExifFormat::U8, 1)
        .add_field(16582, "-1", ExifFormat::U8, 1)
        .add_field(16581, "-2", ExifFormat::U8, 1)
        .add_field(57541, "-3", ExifFormat::U8, 1)
        .add_field(16580, "-4", ExifFormat::U8, 1)
        .add_field(37060, "-5", ExifFormat::U8, 1)
        .add_field(57540, "-6", ExifFormat::U8, 1)
        .add_field(6339, "-7", ExifFormat::U8, 1)
        .add_field(16579, "-8", ExifFormat::U8, 1)
        .add_field(26819, "-9", ExifFormat::U8, 1)
        .add_field(37059, "-10", ExifFormat::U8, 1)
        .add_field(47299, "-11", ExifFormat::U8, 1)
        .add_field(57539, "-12", ExifFormat::U8, 1)
        .add_field(1218, "-13", ExifFormat::U8, 1)
        .add_field(6338, "-14", ExifFormat::U8, 1)
        .add_field(11458, "-15", ExifFormat::U8, 1)
        .add_field(16578, "-16", ExifFormat::U8, 1)
        .add_field(21698, "-17", ExifFormat::U8, 1)
        .add_field(26818, "-18", ExifFormat::U8, 1)
        .add_field(31938, "-19", ExifFormat::U8, 1)
        .add_field(37058, "-20", ExifFormat::U8, 1)
        .build()
}

/// Binary data table: ShotInfoD300S
/// Source lines: 6759-6801
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod300s_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD300S", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(613, "ISO2", ExifFormat::U8, 1)
        .add_field(646, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD700
/// Source lines: 6804-6846
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod700_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD700", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(613, "ISO2", ExifFormat::U8, 1)
        .add_field(647, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD780
/// Source lines: 6849-6879
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod780_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD780", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .build()
}

/// Binary data table: ShotInfoD5000
/// Source lines: 6882-6924
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod5000_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD5000", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(693, "ISO2", ExifFormat::U8, 1)
        .add_field(726, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD5100
/// Source lines: 6927-6958
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod5100_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD5100", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(801, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD5200
/// Source lines: 6961-6995
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod5200_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD5200", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(3032, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD7000
/// Source lines: 6998-7040
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod7000_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD7000", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(800, "ShutterCount", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD7500
/// Source lines: 7043-7073
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod7500_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD7500", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .build()
}

/// Binary data table: ShotInfoD800
/// Source lines: 7076-7642
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod800_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD800", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(1216, "RepeatingFlashOutputExternal", ExifFormat::U8, 1)
        .add_field(1218, "RepeatingFlashRateExternal", ExifFormat::U8, 1)
        .add_field(1219, "RepeatingFlashCountExternal", ExifFormat::U8, 1)
        .add_field(1234, "FlashExposureComp2", ExifFormat::U8, 1)
        .add_field(1242, "RepeatingFlashRateBuilt-in", ExifFormat::U8, 1)
        .add_field(1243, "RepeatingFlashCountBuilt-in", ExifFormat::U8, 1)
        .add_field(1308, "SequenceNumber", ExifFormat::U8, 1)
        .add_field(1531, "ShutterCount", ExifFormat::U32, 1)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(16, "RotationInfoOffset", ExifFormat::U32, 1)
        .add_field(20, "JPGInfoOffset", ExifFormat::U32, 1)
        .add_field(44, "BracketingOffset", ExifFormat::U32, 1)
        .add_field(80, "ShootingMenuOffset", ExifFormat::U32, 1)
        .add_field(88, "CustomSettingsOffset", ExifFormat::U32, 1)
        .add_field(160, "OrientationOffset", ExifFormat::U32, 1)
        .add_field(168, "OtherOffset", ExifFormat::U32, 1)
        .add_field(32, "Interval", ExifFormat::U8, 1)
        // Condition: $$self{Model} eq "NIKON D5" and $$self{FirmwareVersion} ge "1.40"
        .add_field(36, "IntervalFrame", ExifFormat::U8, 1)
        // Condition: $$self{Model} eq "NIKON D5" and $$self{FirmwareVersion} ge "1.40"
        .build()
}

/// Binary data table: ShotInfoD500
/// Source lines: 7196-7274
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod500_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD500", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(16, "RotationInfoOffset", ExifFormat::U32, 1)
        .add_field(20, "JPGInfoOffset", ExifFormat::U32, 1)
        .add_field(44, "BracketingOffset", ExifFormat::U32, 1)
        .add_field(80, "ShootingMenuOffset", ExifFormat::U32, 1)
        .add_field(88, "CustomSettingsOffset", ExifFormat::U32, 1)
        .add_field(160, "OrientationOffset", ExifFormat::U32, 1)
        .add_field(168, "OtherOffset", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD6
/// Source lines: 7655-7704
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod6_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD6", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(164, "IntervalOffset", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD610
/// Source lines: 7863-7890
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod610_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD610", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .build()
}

/// Binary data table: ShotInfoD810
/// Source lines: 7893-13029
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod810_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD810", ExifFormat::U32)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(132, "OrientationOffset", ExifFormat::U32, 1)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(0, "Reset", ExifFormat::U32, 1)
        .add_field(1, "Zoom", ExifFormat::U32, 1)
        .add_field(3, "None", ExifFormat::U32, 1)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(136, "OrientationOffset", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(48, "IntervalOffset", ExifFormat::U32, 1)
        .add_field(56, "PortraitOffset", ExifFormat::U32, 1)
        .add_field(136, "OrientationOffset", ExifFormat::U32, 1)
        // Condition: $$self{Model} =~ /^NIKON Z f\b/i
        .add_field(152, "OrientationOffset", ExifFormat::U32, 1)
        // Condition: $$self{Model} =~ /^NIKON Z (30|5|50|6|6_2|7|7_2|8|fc)\b/i
        .add_field(40, "IntervalFrame", ExifFormat::U16, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(43, "ImageArea", ExifFormat::U32, 1)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(42, "IntervalFrame", ExifFormat::U16, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(3050, "AFAreaInitialWidth", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96
        .add_field(3051, "AFAreaInitialHeight", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96
        .add_field(1, "AutoCaptureCriteria", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(74, "AutoCaptureDistanceFar", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(78, "AutoCaptureDistanceNear", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(95, "AutoCaptureCriteriaMotionDirection", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(99, "AutoCaptureCriteriaMotionSpeed", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(100, "AutoCaptureCriteriaMotionSize", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(105, "AutoCaptureCriteriaSubjectSize", ExifFormat::U32, 1)
        // Condition: $$self{AutoCapturedFrame} and $$self{AutoCapturedFrame} ne 0
        .add_field(0, "RollAngle", ExifFormat::U8, 1)
        .add_field(4, "PitchAngle", ExifFormat::U8, 1)
        .add_field(8, "YawAngle", ExifFormat::U8, 1)
        .add_field(360, "SingleFrame", ExifFormat::U32, 1)
        .add_field(364, "HighFrameRate", ExifFormat::U32, 1)
        .add_field(444, "MultipleExposureMode", ExifFormat::U32, 1)
        .add_field(446, "MultiExposureShots", ExifFormat::U32, 1)
        // Condition: $$self{MultipleExposureMode} != 0
        .add_field(476, "IntervalDurationHours", ExifFormat::U32, 1)
        .add_field(480, "IntervalDurationMinutes", ExifFormat::U32, 1)
        .add_field(484, "IntervalDurationSeconds", ExifFormat::U32, 1)
        .add_field(492, "Intervals", ExifFormat::U32, 1)
        .add_field(496, "ShotsPerInterval", ExifFormat::U32, 1)
        .add_field(500, "IntervalExposureSmoothing", ExifFormat::U8, 1)
        .add_field(502, "IntervalPriority", ExifFormat::U8, 1)
        .add_field(536, "FocusShiftNumberShots", ExifFormat::U32, 1)
        .add_field(540, "FocusShiftStepWidth", ExifFormat::U32, 1)
        .add_field(544, "FocusShiftInterval", ExifFormat::U32, 1)
        .add_field(548, "FocusShiftExposureLock", ExifFormat::U32, 1)
        .add_field(648, "AutoISO", ExifFormat::U32, 1)
        .add_field(650, "ISOAutoHiLimit", ExifFormat::U16, 1)
        .add_field(718, "DiffractionCompensation", ExifFormat::U8, 1)
        .add_field(719, "AutoDistortionControl", ExifFormat::U8, 1)
        .add_field(720, "FlickerReductionShooting", ExifFormat::U32, 1)
        .add_field(722, "NikonMeteringMode", ExifFormat::U32, 1)
        .add_field(724, "FlashControlMode", ExifFormat::U32, 1)
        .add_field(730, "FlashGNDistance", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} == 2
        .add_field(734, "FlashOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} >= 3
        .add_field(742, "FlashWirelessOption", ExifFormat::U32, 1)
        .add_field(744, "FlashRemoteControl", ExifFormat::U32, 1)
        .add_field(748, "FlashMasterControlMode", ExifFormat::U32, 1)
        .add_field(750, "FlashMasterCompensation", ExifFormat::U8, 1)
        // Condition: $$self{FlashGroupOptionsMasterMode}  != 3
        .add_field(754, "FlashMasterOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashGroupOptionsMasterMode}  == 1
        .add_field(832, "AFAreaMode", ExifFormat::U32, 1)
        .add_field(834, "VRMode", ExifFormat::U32, 1)
        .add_field(838, "BracketSet", ExifFormat::U32, 1)
        .add_field(840, "BracketProgram", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(842, "BracketIncrement", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(852, "HDR", ExifFormat::U32, 1)
        .add_field(858, "SecondarySlotFunction", ExifFormat::U32, 1)
        .add_field(864, "HDRLevel", ExifFormat::U32, 1)
        // Condition: $$self{HDR} ne 0
        .add_field(868, "Slot2JpgSize", ExifFormat::U32, 1)
        .add_field(878, "SubjectDetection", ExifFormat::U32, 1)
        .add_field(880, "DynamicAFAreaSize", ExifFormat::U32, 1)
        // Condition: $$self{AFAreaMode} == 2
        .add_field(884, "ToneMap", ExifFormat::U32, 1)
        .add_field(888, "PortraitImpressionBalance", ExifFormat::U32, 1)
        .add_field(902, "HighFrequencyFlickerReduction", ExifFormat::U32, 1)
        .add_field(904, "PixelShiftShooting", ExifFormat::U32, 1)
        .add_field(906, "PixelShiftNumberShots", ExifFormat::U32, 1)
        // Condition: $$self{PixelShiftShooting} > 0
        .add_field(908, "PixelShiftDelay", ExifFormat::U32, 1)
        // Condition: $$self{PixelShiftShooting} > 0
        .add_field(910, "PixelShiftInterval", ExifFormat::U32, 1)
        // Condition: $$self{PixelShiftShooting} > 0
        .add_field(1002, "SubjectDetectionAreaMF", ExifFormat::U32, 1)
        .add_field(1004, "LinkVRToFocusPoint", ExifFormat::U32, 1)
        .add_field(1046, "MovieSlowMotion", ExifFormat::U32, 1)
        .add_field(1050, "MovieType", ExifFormat::U32, 1)
        .add_field(1162, "MovieFrameSize", ExifFormat::U32, 1)
        .add_field(1164, "MovieFrameRate", ExifFormat::U32, 1)
        // Condition: $$self{MovieType}  != 1
        .add_field(2300, "Language", ExifFormat::U32, 1)
        .add_field(2302, "TimeZone", ExifFormat::U32, 1)
        .add_field(2308, "MonitorBrightness", ExifFormat::U32, 1)
        .add_field(2444, "EmptySlotRelease", ExifFormat::U32, 1)
        .add_field(2450, "EnergySavingMode", ExifFormat::U32, 1)
        .add_field(2476, "USBPowerDelivery", ExifFormat::U32, 1)
        .add_field(2480, "SaveFocusPosition", ExifFormat::U32, 1)
        .add_field(2487, "SilentPhotography", ExifFormat::U32, 1)
        .add_field(2496, "AirplaneMode", ExifFormat::U32, 1)
        .add_field(90, "SingleFrame", ExifFormat::U32, 1)
        .add_field(92, "ReleaseMode", ExifFormat::U32, 1)
        .add_field(160, "IntervalDurationHours", ExifFormat::U32, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(164, "IntervalDurationMinutes", ExifFormat::U32, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(168, "IntervalDurationSeconds", ExifFormat::U32, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(176, "Intervals", ExifFormat::U32, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(180, "ShotsPerInterval", ExifFormat::U32, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(184, "IntervalExposureSmoothing", ExifFormat::U8, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(186, "IntervalPriority", ExifFormat::U8, 1)
        // Condition: $$self{IntervalShooting} > 0
        .add_field(220, "FocusShiftNumberShots", ExifFormat::U32, 1)
        .add_field(224, "FocusShiftStepWidth", ExifFormat::U32, 1)
        .add_field(228, "FocusShiftInterval", ExifFormat::U32, 1)
        .add_field(232, "FocusShiftExposureLock", ExifFormat::U32, 1)
        .add_field(322, "DiffractionCompensation", ExifFormat::U8, 1)
        .add_field(323, "AutoDistortionControl", ExifFormat::U8, 1)
        .add_field(326, "NikonMeteringMode", ExifFormat::U32, 1)
        .add_field(328, "FlashControlMode", ExifFormat::U32, 1)
        .add_field(334, "FlashGNDistance", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} == 2
        .add_field(338, "FlashOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} >= 3
        .add_field(346, "FlashWirelessOption", ExifFormat::U32, 1)
        .add_field(348, "FlashRemoteControl", ExifFormat::U32, 1)
        .add_field(352, "FlashMasterControlMode", ExifFormat::U32, 1)
        .add_field(354, "FlashMasterCompensation", ExifFormat::U8, 1)
        // Condition: $$self{FlashGroupOptionsMasterMode}  != 3
        .add_field(358, "FlashMasterOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashGroupOptionsMasterMode}  == 1
        .add_field(502, "MovieFrameSize", ExifFormat::U32, 1)
        .add_field(504, "MovieFrameRate", ExifFormat::U32, 1)
        .add_field(506, "MovieSlowMotion", ExifFormat::U32, 1)
        .add_field(516, "MovieISOAutoManualMode", ExifFormat::U32, 1)
        // Condition: $$self{Model} =~ /^NIKON 7/
        .add_field(568, "MovieActiveD-Lighting", ExifFormat::U32, 1)
        .add_field(572, "MovieHighISONoiseReduction", ExifFormat::U32, 1)
        .add_field(574, "MovieVignetteControl", ExifFormat::U32, 1)
        .add_field(576, "MovieVignetteControlSameAsPhoto", ExifFormat::U32, 1)
        .add_field(577, "MovieDiffractionCompensation", ExifFormat::U32, 1)
        .add_field(578, "MovieAutoDistortionControl", ExifFormat::U32, 1)
        .add_field(584, "MovieFocusMode", ExifFormat::U32, 1)
        .add_field(591, "MovieVibrationReductionSameAsPhoto", ExifFormat::U32, 1)
        .add_field(858, "HDMIOutputN-Log", ExifFormat::U32, 1)
        // Condition: $$self{HDMIBitDepth} and $$self{HDMIBitDepth} == 2
        .add_field(72, "HighFrameRate", ExifFormat::U32, 1)
        .add_field(152, "MultipleExposureMode", ExifFormat::U32, 1)
        .add_field(154, "MultiExposureShots", ExifFormat::U32, 1)
        // Condition: $$self{MultipleExposureMode} != 0
        .add_field(184, "IntervalDurationHours", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(188, "IntervalDurationMinutes", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(192, "IntervalDurationSeconds", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(200, "Intervals", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(204, "ShotsPerInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(208, "IntervalExposureSmoothing", ExifFormat::U8, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(210, "IntervalPriority", ExifFormat::U8, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(244, "FocusShiftNumberShots", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(248, "FocusShiftStepWidth", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(252, "FocusShiftInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(256, "FocusShiftExposureLock", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(286, "PhotoShootingMenuBank", ExifFormat::U32, 1)
        .add_field(288, "ExtendedMenuBanks", ExifFormat::U32, 1)
        .add_field(324, "PhotoShootingMenuBankImageArea", ExifFormat::U32, 1)
        .add_field(338, "AutoISO", ExifFormat::U32, 1)
        .add_field(340, "ISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(342, "ISOAutoFlashLimit", ExifFormat::U32, 1)
        .add_field(350, "ISOAutoShutterTime", ExifFormat::I16, 1)
        .add_field(432, "MovieVignetteControl", ExifFormat::U32, 1)
        .add_field(434, "DiffractionCompensation", ExifFormat::U32, 1)
        .add_field(436, "FlickerReductionShooting", ExifFormat::U32, 1)
        .add_field(440, "FlashControlMode", ExifFormat::U32, 1)
        .add_field(548, "AFAreaMode", ExifFormat::U32, 1)
        .add_field(550, "VRMode", ExifFormat::U32, 1)
        .add_field(554, "BracketSet", ExifFormat::U32, 1)
        .add_field(556, "BracketProgram", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(558, "BracketIncrement", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(570, "HDR", ExifFormat::U32, 1)
        .add_field(576, "SecondarySlotFunction", ExifFormat::U32, 1)
        .add_field(582, "HDRLevel", ExifFormat::U32, 1)
        // Condition: $$self{HDR} ne 0
        .add_field(586, "Slot2JpgSize", ExifFormat::U32, 1)
        .add_field(592, "DXCropAlert", ExifFormat::U32, 1)
        .add_field(594, "SubjectDetection", ExifFormat::U32, 1)
        .add_field(596, "DynamicAFAreaSize", ExifFormat::U32, 1)
        // Condition: $$self{AFAreaMode} == 2
        .add_field(618, "ToneMap", ExifFormat::U32, 1)
        .add_field(622, "PortraitImpressionBalance", ExifFormat::U32, 1)
        .add_field(636, "HighFrequencyFlickerReduction", ExifFormat::U32, 1)
        .add_field(730, "MovieImageArea", ExifFormat::U32, 1)
        .add_field(740, "MovieType", ExifFormat::U32, 1)
        .add_field(742, "MovieISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(744, "MovieISOAutoControlManualMode", ExifFormat::U32, 1)
        .add_field(746, "MovieISOAutoManualMode", ExifFormat::U32, 1)
        .add_field(820, "MovieActiveD-Lighting", ExifFormat::U32, 1)
        .add_field(822, "MovieHighISONoiseReduction", ExifFormat::U32, 1)
        .add_field(828, "MovieFlickerReduction", ExifFormat::U32, 1)
        .add_field(830, "MovieMeteringMode", ExifFormat::U32, 1)
        .add_field(832, "MovieFocusMode", ExifFormat::U32, 1)
        .add_field(834, "MovieAFAreaMode", ExifFormat::U32, 1)
        .add_field(836, "MovieVRMode", ExifFormat::U32, 1)
        .add_field(840, "MovieElectronicVR", ExifFormat::U32, 1)
        .add_field(842, "MovieSoundRecording", ExifFormat::U32, 1)
        .add_field(844, "MicrophoneSensitivity", ExifFormat::U32, 1)
        .add_field(846, "MicrophoneAttenuator", ExifFormat::U32, 1)
        .add_field(848, "MicrophoneFrequencyResponse", ExifFormat::U32, 1)
        .add_field(850, "WindNoiseReduction", ExifFormat::U32, 1)
        .add_field(882, "MovieFrameSize", ExifFormat::U32, 1)
        .add_field(884, "MovieFrameRate", ExifFormat::U32, 1)
        .add_field(886, "MicrophoneJackPower", ExifFormat::U32, 1)
        .add_field(887, "MovieDXCropAlert", ExifFormat::U32, 1)
        .add_field(888, "MovieSubjectDetection", ExifFormat::U32, 1)
        .add_field(896, "MovieHighResZoom", ExifFormat::U32, 1)
        .add_field(1684, "TimeZone", ExifFormat::U32, 1)
        .add_field(1690, "MonitorBrightness", ExifFormat::U32, 1)
        .add_field(1698, "Language", ExifFormat::U32, 1)
        .add_field(1712, "AFFineTune", ExifFormat::U32, 1)
        .add_field(1716, "NonCPULens1FocalLength", ExifFormat::U16, 1)
        .add_field(1718, "NonCPULens2FocalLength", ExifFormat::U16, 1)
        .add_field(1720, "NonCPULens3FocalLength", ExifFormat::U16, 1)
        .add_field(1722, "NonCPULens4FocalLength", ExifFormat::U16, 1)
        .add_field(1724, "NonCPULens5FocalLength", ExifFormat::U16, 1)
        .add_field(1726, "NonCPULens6FocalLength", ExifFormat::U16, 1)
        .add_field(1728, "NonCPULens7FocalLength", ExifFormat::U16, 1)
        .add_field(1730, "NonCPULens8FocalLength", ExifFormat::U16, 1)
        .add_field(1732, "NonCPULens9FocalLength", ExifFormat::U16, 1)
        .add_field(1734, "NonCPULens10FocalLength", ExifFormat::U16, 1)
        .add_field(1736, "NonCPULens11FocalLength", ExifFormat::U16, 1)
        .add_field(1738, "NonCPULens12FocalLength", ExifFormat::U16, 1)
        .add_field(1740, "NonCPULens13FocalLength", ExifFormat::U16, 1)
        .add_field(1742, "NonCPULens14FocalLength", ExifFormat::U16, 1)
        .add_field(1744, "NonCPULens15FocalLength", ExifFormat::U16, 1)
        .add_field(1746, "NonCPULens16FocalLength", ExifFormat::U16, 1)
        .add_field(1748, "NonCPULens17FocalLength", ExifFormat::U16, 1)
        .add_field(1750, "NonCPULens18FocalLength", ExifFormat::U16, 1)
        .add_field(1752, "NonCPULens19FocalLength", ExifFormat::U16, 1)
        .add_field(1754, "NonCPULens20FocalLength", ExifFormat::U16, 1)
        .add_field(1756, "NonCPULens1MaxAperture", ExifFormat::U32, 1)
        .add_field(1758, "NonCPULens2MaxAperture", ExifFormat::U32, 1)
        .add_field(1760, "NonCPULens3MaxAperture", ExifFormat::U32, 1)
        .add_field(1762, "NonCPULens4MaxAperture", ExifFormat::U32, 1)
        .add_field(1764, "NonCPULens5MaxAperture", ExifFormat::U32, 1)
        .add_field(1766, "NonCPULens6MaxAperture", ExifFormat::U32, 1)
        .add_field(1768, "NonCPULens7MaxAperture", ExifFormat::U32, 1)
        .add_field(1770, "NonCPULens8MaxAperture", ExifFormat::U32, 1)
        .add_field(1772, "NonCPULens9MaxAperture", ExifFormat::U32, 1)
        .add_field(1774, "NonCPULens10MaxAperture", ExifFormat::U32, 1)
        .add_field(1776, "NonCPULens11MaxAperture", ExifFormat::U32, 1)
        .add_field(1778, "NonCPULens12MaxAperture", ExifFormat::U32, 1)
        .add_field(1780, "NonCPULens13MaxAperture", ExifFormat::U32, 1)
        .add_field(1782, "NonCPULens14MaxAperture", ExifFormat::U32, 1)
        .add_field(1784, "NonCPULens15MaxAperture", ExifFormat::U32, 1)
        .add_field(1786, "NonCPULens16MaxAperture", ExifFormat::U32, 1)
        .add_field(1788, "NonCPULens17MaxAperture", ExifFormat::U32, 1)
        .add_field(1790, "NonCPULens18MaxAperture", ExifFormat::U32, 1)
        .add_field(1792, "NonCPULens19MaxAperture", ExifFormat::U32, 1)
        .add_field(1794, "NonCPULens20MaxAperture", ExifFormat::U32, 1)
        .add_field(1808, "HDMIOutputResolution", ExifFormat::U32, 1)
        .add_field(1826, "AirplaneMode", ExifFormat::U32, 1)
        .add_field(1827, "EmptySlotRelease", ExifFormat::U32, 1)
        .add_field(1862, "EnergySavingMode", ExifFormat::U32, 1)
        .add_field(1890, "USBPowerDelivery", ExifFormat::U32, 1)
        .add_field(1899, "SensorShield", ExifFormat::U32, 1)
        .add_field(1698, "Language", ExifFormat::U32, 1)
        .add_field(1700, "TimeZone", ExifFormat::U32, 1)
        .add_field(1706, "MonitorBrightness", ExifFormat::U32, 1)
        .add_field(1728, "AFFineTune", ExifFormat::U32, 1)
        .add_field(1732, "NonCPULens1FocalLength", ExifFormat::U16, 1)
        .add_field(1734, "NonCPULens2FocalLength", ExifFormat::U16, 1)
        .add_field(1736, "NonCPULens3FocalLength", ExifFormat::U16, 1)
        .add_field(1738, "NonCPULens4FocalLength", ExifFormat::U16, 1)
        .add_field(1740, "NonCPULens5FocalLength", ExifFormat::U16, 1)
        .add_field(1742, "NonCPULens6FocalLength", ExifFormat::U16, 1)
        .add_field(1744, "NonCPULens7FocalLength", ExifFormat::U16, 1)
        .add_field(1746, "NonCPULens8FocalLength", ExifFormat::U16, 1)
        .add_field(1748, "NonCPULens9FocalLength", ExifFormat::U16, 1)
        .add_field(1750, "NonCPULens10FocalLength", ExifFormat::U16, 1)
        .add_field(1752, "NonCPULens11FocalLength", ExifFormat::U16, 1)
        .add_field(1754, "NonCPULens12FocalLength", ExifFormat::U16, 1)
        .add_field(1756, "NonCPULens13FocalLength", ExifFormat::U16, 1)
        .add_field(1758, "NonCPULens14FocalLength", ExifFormat::U16, 1)
        .add_field(1760, "NonCPULens15FocalLength", ExifFormat::U16, 1)
        .add_field(1762, "NonCPULens16FocalLength", ExifFormat::U16, 1)
        .add_field(1764, "NonCPULens17FocalLength", ExifFormat::U16, 1)
        .add_field(1766, "NonCPULens18FocalLength", ExifFormat::U16, 1)
        .add_field(1768, "NonCPULens19FocalLength", ExifFormat::U16, 1)
        .add_field(1770, "NonCPULens20FocalLength", ExifFormat::U16, 1)
        .add_field(1812, "NonCPULens1MaxAperture", ExifFormat::U32, 1)
        .add_field(1816, "NonCPULens2MaxAperture", ExifFormat::U32, 1)
        .add_field(1820, "NonCPULens3MaxAperture", ExifFormat::U32, 1)
        .add_field(1824, "NonCPULens4MaxAperture", ExifFormat::U32, 1)
        .add_field(1828, "NonCPULens5MaxAperture", ExifFormat::U32, 1)
        .add_field(1832, "NonCPULens6MaxAperture", ExifFormat::U32, 1)
        .add_field(1836, "NonCPULens7MaxAperture", ExifFormat::U32, 1)
        .add_field(1840, "NonCPULens8MaxAperture", ExifFormat::U32, 1)
        .add_field(1844, "NonCPULens9MaxAperture", ExifFormat::U32, 1)
        .add_field(1848, "NonCPULens10MaxAperture", ExifFormat::U32, 1)
        .add_field(1852, "NonCPULens11MaxAperture", ExifFormat::U32, 1)
        .add_field(1856, "NonCPULens12MaxAperture", ExifFormat::U32, 1)
        .add_field(1860, "NonCPULens13MaxAperture", ExifFormat::U32, 1)
        .add_field(1864, "NonCPULens14MaxAperture", ExifFormat::U32, 1)
        .add_field(1868, "NonCPULens15MaxAperture", ExifFormat::U32, 1)
        .add_field(1872, "NonCPULens16MaxAperture", ExifFormat::U32, 1)
        .add_field(1876, "NonCPULens17MaxAperture", ExifFormat::U32, 1)
        .add_field(1880, "NonCPULens18MaxAperture", ExifFormat::U32, 1)
        .add_field(1884, "NonCPULens19MaxAperture", ExifFormat::U32, 1)
        .add_field(1888, "NonCPULens20MaxAperture", ExifFormat::U32, 1)
        .add_field(1824, "HDMIOutputResolution", ExifFormat::U32, 1)
        .add_field(1842, "AirplaneMode", ExifFormat::U32, 1)
        .add_field(1843, "EmptySlotRelease", ExifFormat::U32, 1)
        .add_field(1878, "EnergySavingMode", ExifFormat::U32, 1)
        .add_field(1906, "USBPowerDelivery", ExifFormat::U32, 1)
        .add_field(1915, "SensorShield", ExifFormat::U32, 1)
        .add_field(2046, "PixelShiftShooting", ExifFormat::U32, 1)
        .add_field(2048, "PixelShiftNumberShots", ExifFormat::U32, 1)
        // Condition: $$self{PixelShiftShooting} > 0
        .add_field(2050, "PixelShiftDelay", ExifFormat::U32, 1)
        // Condition: $$self{PixelShiftShooting} > 0
        .add_field(2052, "PlaybackButton", ExifFormat::U32, 1)
        .add_field(2054, "WBButton", ExifFormat::U32, 1)
        .add_field(2056, "BracketButton", ExifFormat::U32, 1)
        .add_field(2058, "LensFunc1ButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2060, "LensFunc2ButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2062, "PlaybackButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2064, "BracketButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(140, "MultipleExposureMode", ExifFormat::U32, 1)
        .add_field(142, "MultiExposureShots", ExifFormat::U32, 1)
        // Condition: $$self{MultipleExposureMode} != 0
        .add_field(188, "Intervals", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(192, "ShotsPerInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(232, "FocusShiftNumberShots", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(236, "FocusShiftStepWidth", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(240, "FocusShiftInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(244, "FocusShiftExposureLock", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(274, "PhotoShootingMenuBank", ExifFormat::U32, 1)
        .add_field(276, "ExtendedMenuBanks", ExifFormat::U32, 1)
        .add_field(308, "PhotoShootingMenuBankImageArea", ExifFormat::U32, 1)
        .add_field(322, "AutoISO", ExifFormat::U32, 1)
        .add_field(324, "ISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(326, "ISOAutoFlashLimit", ExifFormat::U32, 1)
        .add_field(334, "ISOAutoShutterTime", ExifFormat::I16, 1)
        .add_field(416, "MovieVignetteControl", ExifFormat::U32, 1)
        .add_field(418, "DiffractionCompensation", ExifFormat::U32, 1)
        .add_field(420, "FlickerReductionShooting", ExifFormat::U32, 1)
        .add_field(424, "FlashControlMode", ExifFormat::U32, 1)
        .add_field(426, "FlashMasterCompensation", ExifFormat::U8, 1)
        .add_field(430, "FlashGNDistance", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} == 2
        .add_field(434, "FlashOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} >= 3
        .add_field(444, "FlashRemoteControl", ExifFormat::U32, 1)
        .add_field(456, "FlashWirelessOption", ExifFormat::U32, 1)
        .add_field(528, "AFAreaMode", ExifFormat::U32, 1)
        .add_field(530, "VRMode", ExifFormat::U32, 1)
        .add_field(534, "BracketSet", ExifFormat::U32, 1)
        .add_field(536, "BracketProgram", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(538, "BracketIncrement", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(556, "SecondarySlotFunction", ExifFormat::U32, 1)
        .add_field(572, "DXCropAlert", ExifFormat::U32, 1)
        .add_field(574, "SubjectDetection", ExifFormat::U32, 1)
        .add_field(576, "DynamicAFAreaSize", ExifFormat::U32, 1)
        // Condition: $$self{AFAreaMode} == 2
        .add_field(604, "MovieImageArea", ExifFormat::U32, 1)
        .add_field(614, "MovieType", ExifFormat::U32, 1)
        .add_field(616, "MovieISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(618, "MovieISOAutoControlManualMode", ExifFormat::U32, 1)
        .add_field(620, "MovieISOAutoManualMode", ExifFormat::U32, 1)
        .add_field(696, "MovieActiveD-Lighting", ExifFormat::U32, 1)
        .add_field(698, "MovieHighISONoiseReduction", ExifFormat::U32, 1)
        .add_field(704, "MovieFlickerReduction", ExifFormat::U32, 1)
        .add_field(706, "MovieMeteringMode", ExifFormat::U32, 1)
        .add_field(708, "MovieFocusMode", ExifFormat::U32, 1)
        .add_field(710, "MovieAFAreaMode", ExifFormat::U32, 1)
        .add_field(712, "MovieVRMode", ExifFormat::U32, 1)
        .add_field(716, "MovieElectronicVR", ExifFormat::U32, 1)
        .add_field(718, "MovieSoundRecording", ExifFormat::U32, 1)
        .add_field(720, "MicrophoneSensitivity", ExifFormat::U32, 1)
        .add_field(722, "MicrophoneAttenuator", ExifFormat::U32, 1)
        .add_field(724, "MicrophoneFrequencyResponse", ExifFormat::U32, 1)
        .add_field(726, "WindNoiseReduction", ExifFormat::U32, 1)
        .add_field(748, "MovieToneMap", ExifFormat::U32, 1)
        .add_field(754, "MovieFrameSize", ExifFormat::U32, 1)
        .add_field(756, "MovieFrameRate", ExifFormat::U32, 1)
        .add_field(762, "MicrophoneJackPower", ExifFormat::U32, 1)
        .add_field(763, "MovieDXCropAlert", ExifFormat::U32, 1)
        .add_field(764, "MovieSubjectDetection", ExifFormat::U32, 1)
        .add_field(1426, "Language", ExifFormat::U32, 1)
        .add_field(1428, "TimeZone", ExifFormat::U32, 1)
        .add_field(1434, "MonitorBrightness", ExifFormat::U32, 1)
        .add_field(1456, "AFFineTune", ExifFormat::U32, 1)
        .add_field(1552, "HDMIOutputResolution", ExifFormat::U32, 1)
        .add_field(1565, "SetClockFromLocationData", ExifFormat::U32, 1)
        .add_field(1572, "AirplaneMode", ExifFormat::U32, 1)
        .add_field(1573, "EmptySlotRelease", ExifFormat::U32, 1)
        .add_field(1608, "EnergySavingMode", ExifFormat::U32, 1)
        .add_field(1632, "RecordLocationData", ExifFormat::U32, 1)
        .add_field(1636, "USBPowerDelivery", ExifFormat::U32, 1)
        .add_field(1645, "SensorShield", ExifFormat::U32, 1)
        .add_field(72, "HighFrameRate", ExifFormat::U32, 1)
        .add_field(154, "MultipleExposureMode", ExifFormat::U32, 1)
        .add_field(156, "MultiExposureShots", ExifFormat::U32, 1)
        // Condition: $$self{MultipleExposureMode} != 0
        .add_field(204, "Intervals", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(208, "ShotsPerInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(248, "FocusShiftNumberShots", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(252, "FocusShiftStepWidth", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(256, "FocusShiftInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(260, "FocusShiftExposureLock", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(290, "PhotoShootingMenuBank", ExifFormat::U32, 1)
        .add_field(292, "ExtendedMenuBanks", ExifFormat::U32, 1)
        .add_field(328, "PhotoShootingMenuBankImageArea", ExifFormat::U32, 1)
        .add_field(342, "AutoISO", ExifFormat::U32, 1)
        .add_field(344, "ISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(346, "ISOAutoFlashLimit", ExifFormat::U32, 1)
        .add_field(354, "ISOAutoShutterTime", ExifFormat::I16, 1)
        .add_field(436, "MovieVignetteControl", ExifFormat::U32, 1)
        .add_field(438, "DiffractionCompensation", ExifFormat::U32, 1)
        .add_field(440, "FlickerReductionShooting", ExifFormat::U32, 1)
        .add_field(444, "FlashControlMode", ExifFormat::U32, 1)
        .add_field(446, "FlashMasterCompensation", ExifFormat::U8, 1)
        .add_field(450, "FlashGNDistance", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} == 2
        .add_field(454, "FlashOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} >= 3
        .add_field(548, "AFAreaMode", ExifFormat::U32, 1)
        .add_field(550, "VRMode", ExifFormat::U32, 1)
        .add_field(554, "BracketSet", ExifFormat::U32, 1)
        .add_field(556, "BracketProgram", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(558, "BracketIncrement", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(576, "SecondarySlotFunction", ExifFormat::U32, 1)
        .add_field(592, "DXCropAlert", ExifFormat::U32, 1)
        .add_field(594, "SubjectDetection", ExifFormat::U32, 1)
        .add_field(596, "DynamicAFAreaSize", ExifFormat::U32, 1)
        // Condition: $$self{AFAreaMode} == 2
        .add_field(636, "HighFrequencyFlickerReduction", ExifFormat::U32, 1)
        .add_field(646, "MovieImageArea", ExifFormat::U32, 1)
        .add_field(656, "MovieType", ExifFormat::U32, 1)
        .add_field(658, "MovieISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(660, "MovieISOAutoControlManualMode", ExifFormat::U32, 1)
        .add_field(662, "MovieISOAutoManualMode", ExifFormat::U32, 1)
        .add_field(736, "MovieActiveD-Lighting", ExifFormat::U32, 1)
        .add_field(738, "MovieHighISONoiseReduction", ExifFormat::U32, 1)
        .add_field(744, "MovieFlickerReduction", ExifFormat::U32, 1)
        .add_field(746, "MovieMeteringMode", ExifFormat::U32, 1)
        .add_field(748, "MovieFocusMode", ExifFormat::U32, 1)
        .add_field(750, "MovieAFAreaMode", ExifFormat::U32, 1)
        .add_field(752, "MovieVRMode", ExifFormat::U32, 1)
        .add_field(756, "MovieElectronicVR", ExifFormat::U32, 1)
        .add_field(758, "MovieSoundRecording", ExifFormat::U32, 1)
        .add_field(760, "MicrophoneSensitivity", ExifFormat::U32, 1)
        .add_field(762, "MicrophoneAttenuator", ExifFormat::U32, 1)
        .add_field(764, "MicrophoneFrequencyResponse", ExifFormat::U32, 1)
        .add_field(766, "WindNoiseReduction", ExifFormat::U32, 1)
        .add_field(788, "MovieToneMap", ExifFormat::U32, 1)
        .add_field(794, "MovieFrameSize", ExifFormat::U32, 1)
        .add_field(796, "MovieFrameRate", ExifFormat::U32, 1)
        .add_field(802, "MicrophoneJackPower", ExifFormat::U32, 1)
        .add_field(803, "MovieDXCropAlert", ExifFormat::U32, 1)
        .add_field(804, "MovieSubjectDetection", ExifFormat::U32, 1)
        .add_field(812, "MovieHighResZoom", ExifFormat::U32, 1)
        .add_field(1474, "Language", ExifFormat::U32, 1)
        .add_field(1476, "TimeZone", ExifFormat::U32, 1)
        .add_field(1482, "MonitorBrightness", ExifFormat::U32, 1)
        .add_field(1504, "AFFineTune", ExifFormat::U32, 1)
        .add_field(1600, "HDMIOutputResolution", ExifFormat::U32, 1)
        .add_field(1613, "SetClockFromLocationData", ExifFormat::U32, 1)
        .add_field(1620, "AirplaneMode", ExifFormat::U32, 1)
        .add_field(1621, "EmptySlotRelease", ExifFormat::U32, 1)
        .add_field(1656, "EnergySavingMode", ExifFormat::U32, 1)
        .add_field(1680, "RecordLocationData", ExifFormat::U32, 1)
        .add_field(1684, "USBPowerDelivery", ExifFormat::U32, 1)
        .add_field(1693, "SensorShield", ExifFormat::U32, 1)
        .add_field(1754, "FocusShiftAutoReset", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(72, "HighFrameRate", ExifFormat::U32, 1)
        .add_field(154, "MultipleExposureMode", ExifFormat::U32, 1)
        .add_field(156, "MultiExposureShots", ExifFormat::U32, 1)
        // Condition: $$self{MultipleExposureMode} != 0
        .add_field(204, "Intervals", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(208, "ShotsPerInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .add_field(248, "FocusShiftNumberShots", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(252, "FocusShiftStepWidth", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(256, "FocusShiftInterval", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(260, "FocusShiftExposureLock", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(290, "PhotoShootingMenuBank", ExifFormat::U32, 1)
        .add_field(292, "ExtendedMenuBanks", ExifFormat::U32, 1)
        .add_field(328, "PhotoShootingMenuBankImageArea", ExifFormat::U32, 1)
        .add_field(342, "AutoISO", ExifFormat::U32, 1)
        .add_field(344, "ISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(346, "ISOAutoFlashLimit", ExifFormat::U32, 1)
        .add_field(354, "ISOAutoShutterTime", ExifFormat::I16, 1)
        .add_field(436, "MovieVignetteControl", ExifFormat::U32, 1)
        .add_field(438, "DiffractionCompensation", ExifFormat::U32, 1)
        .add_field(440, "FlickerReductionShooting", ExifFormat::U32, 1)
        .add_field(444, "FlashControlMode", ExifFormat::U32, 1)
        .add_field(446, "FlashMasterCompensation", ExifFormat::U8, 1)
        .add_field(450, "FlashGNDistance", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} == 2
        .add_field(454, "FlashOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} >= 3
        .add_field(548, "AFAreaMode", ExifFormat::U32, 1)
        .add_field(550, "VRMode", ExifFormat::U32, 1)
        .add_field(554, "BracketSet", ExifFormat::U32, 1)
        .add_field(556, "BracketProgram", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(558, "BracketIncrement", ExifFormat::U32, 1)
        // Condition: $$self{BracketSet} < 3
        .add_field(570, "HDR", ExifFormat::U32, 1)
        .add_field(576, "SecondarySlotFunction", ExifFormat::U32, 1)
        .add_field(582, "HDRLevel", ExifFormat::U32, 1)
        // Condition: $$self{HDR} ne 0
        .add_field(586, "Slot2JpgSize", ExifFormat::U32, 1)
        .add_field(592, "DXCropAlert", ExifFormat::U32, 1)
        .add_field(594, "SubjectDetection", ExifFormat::U32, 1)
        .add_field(596, "DynamicAFAreaSize", ExifFormat::U32, 1)
        // Condition: $$self{AFAreaMode} == 2
        .add_field(636, "HighFrequencyFlickerReduction", ExifFormat::U32, 1)
        .add_field(646, "MovieImageArea", ExifFormat::U32, 1)
        .add_field(656, "MovieType", ExifFormat::U32, 1)
        .add_field(658, "MovieISOAutoHiLimit", ExifFormat::U32, 1)
        .add_field(660, "MovieISOAutoControlManualMode", ExifFormat::U32, 1)
        .add_field(662, "MovieISOAutoManualMode", ExifFormat::U32, 1)
        .add_field(736, "MovieActiveD-Lighting", ExifFormat::U32, 1)
        .add_field(738, "MovieHighISONoiseReduction", ExifFormat::U32, 1)
        .add_field(744, "MovieFlickerReduction", ExifFormat::U32, 1)
        .add_field(746, "MovieMeteringMode", ExifFormat::U32, 1)
        .add_field(748, "MovieFocusMode", ExifFormat::U32, 1)
        .add_field(750, "MovieAFAreaMode", ExifFormat::U32, 1)
        .add_field(752, "MovieVRMode", ExifFormat::U32, 1)
        .add_field(756, "MovieElectronicVR", ExifFormat::U32, 1)
        .add_field(758, "MovieSoundRecording", ExifFormat::U32, 1)
        .add_field(760, "MicrophoneSensitivity", ExifFormat::U32, 1)
        .add_field(762, "MicrophoneAttenuator", ExifFormat::U32, 1)
        .add_field(764, "MicrophoneFrequencyResponse", ExifFormat::U32, 1)
        .add_field(766, "WindNoiseReduction", ExifFormat::U32, 1)
        .add_field(788, "MovieToneMap", ExifFormat::U32, 1)
        .add_field(794, "MovieFrameSize", ExifFormat::U32, 1)
        .add_field(796, "MovieFrameRate", ExifFormat::U32, 1)
        .add_field(802, "MicrophoneJackPower", ExifFormat::U32, 1)
        .add_field(803, "MovieDXCropAlert", ExifFormat::U32, 1)
        .add_field(804, "MovieSubjectDetection", ExifFormat::U32, 1)
        .add_field(812, "MovieHighResZoom", ExifFormat::U32, 1)
        .add_field(1498, "Language", ExifFormat::U32, 1)
        .add_field(1500, "TimeZone", ExifFormat::U32, 1)
        .add_field(1506, "MonitorBrightness", ExifFormat::U32, 1)
        .add_field(1528, "AFFineTune", ExifFormat::U32, 1)
        .add_field(1532, "NonCPULens1FocalLength", ExifFormat::I16, 1)
        .add_field(1536, "NonCPULens2FocalLength", ExifFormat::I16, 1)
        .add_field(1540, "NonCPULens3FocalLength", ExifFormat::I16, 1)
        .add_field(1544, "NonCPULens4FocalLength", ExifFormat::I16, 1)
        .add_field(1548, "NonCPULens5FocalLength", ExifFormat::I16, 1)
        .add_field(1552, "NonCPULens6FocalLength", ExifFormat::I16, 1)
        .add_field(1556, "NonCPULens7FocalLength", ExifFormat::I16, 1)
        .add_field(1560, "NonCPULens8FocalLength", ExifFormat::I16, 1)
        .add_field(1564, "NonCPULens9FocalLength", ExifFormat::I16, 1)
        .add_field(1568, "NonCPULens10FocalLength", ExifFormat::I16, 1)
        .add_field(1572, "NonCPULens11FocalLength", ExifFormat::I16, 1)
        .add_field(1576, "NonCPULens12FocalLength", ExifFormat::I16, 1)
        .add_field(1580, "NonCPULens13FocalLength", ExifFormat::I16, 1)
        .add_field(1584, "NonCPULens14FocalLength", ExifFormat::I16, 1)
        .add_field(1588, "NonCPULens15FocalLength", ExifFormat::I16, 1)
        .add_field(1592, "NonCPULens16FocalLength", ExifFormat::I16, 1)
        .add_field(1596, "NonCPULens17FocalLength", ExifFormat::I16, 1)
        .add_field(1600, "NonCPULens18FocalLength", ExifFormat::I16, 1)
        .add_field(1604, "NonCPULens19FocalLength", ExifFormat::I16, 1)
        .add_field(1608, "NonCPULens20FocalLength", ExifFormat::I16, 1)
        .add_field(1612, "NonCPULens1MaxAperture", ExifFormat::I16, 1)
        .add_field(1616, "NonCPULens2MaxAperture", ExifFormat::I16, 1)
        .add_field(1620, "NonCPULens3MaxAperture", ExifFormat::I16, 1)
        .add_field(1624, "NonCPULens4MaxAperture", ExifFormat::I16, 1)
        .add_field(1628, "NonCPULens5MaxAperture", ExifFormat::I16, 1)
        .add_field(1632, "NonCPULens6MaxAperture", ExifFormat::I16, 1)
        .add_field(1636, "NonCPULens7MaxAperture", ExifFormat::I16, 1)
        .add_field(1640, "NonCPULens8MaxAperture", ExifFormat::I16, 1)
        .add_field(1644, "NonCPULens9MaxAperture", ExifFormat::I16, 1)
        .add_field(1648, "NonCPULens10MaxAperture", ExifFormat::I16, 1)
        .add_field(1652, "NonCPULens11MaxAperture", ExifFormat::I16, 1)
        .add_field(1656, "NonCPULens12MaxAperture", ExifFormat::I16, 1)
        .add_field(1660, "NonCPULens13MaxAperture", ExifFormat::I16, 1)
        .add_field(1664, "NonCPULens14MaxAperture", ExifFormat::I16, 1)
        .add_field(1668, "NonCPULens15MaxAperture", ExifFormat::I16, 1)
        .add_field(1672, "NonCPULens16MaxAperture", ExifFormat::I16, 1)
        .add_field(1676, "NonCPULens17MaxAperture", ExifFormat::I16, 1)
        .add_field(1680, "NonCPULens18MaxAperture", ExifFormat::I16, 1)
        .add_field(1684, "NonCPULens19MaxAperture", ExifFormat::I16, 1)
        .add_field(1688, "NonCPULens20MaxAperture", ExifFormat::I16, 1)
        .add_field(1704, "HDMIOutputResolution", ExifFormat::U32, 1)
        .add_field(1717, "SetClockFromLocationData", ExifFormat::U32, 1)
        .add_field(1724, "AirplaneMode", ExifFormat::U32, 1)
        .add_field(1725, "EmptySlotRelease", ExifFormat::U32, 1)
        .add_field(1760, "EnergySavingMode", ExifFormat::U32, 1)
        .add_field(1784, "RecordLocationData", ExifFormat::U32, 1)
        .add_field(1788, "USBPowerDelivery", ExifFormat::U32, 1)
        .add_field(1797, "SensorShield", ExifFormat::U32, 1)
        .add_field(1864, "FocusShiftAutoReset", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{FocusShiftShooting} > 0
        .add_field(1938, "VerticalISOButton", ExifFormat::U32, 1)
        .add_field(1940, "ExposureCompensationButton", ExifFormat::U32, 1)
        .add_field(1942, "ISOButton", ExifFormat::U32, 1)
        .add_field(2002, "ViewModeShowEffectsOfSettings", ExifFormat::U32, 1)
        .add_field(2004, "DispButton", ExifFormat::U32, 1)
        .add_field(2048, "ExposureDelay", ExifFormat::U8, 1)
        .add_field(2052, "CommandDialFrameAdvanceZoom", ExifFormat::U32, 1)
        // Condition: $$self{FirmwareVersion} and $$self{FirmwareVersion} ge "05.00"
        .add_field(2054, "SubCommandDialFrameAdvanceZoom", ExifFormat::U32, 1)
        // Condition: $$self{FirmwareVersion} and $$self{FirmwareVersion} ge "05.00"
        .add_field(2056, "PlaybackButton", ExifFormat::U32, 1)
        .add_field(2058, "WBButton", ExifFormat::U32, 1)
        .add_field(2060, "BracketButton", ExifFormat::U32, 1)
        .add_field(2062, "FlashModeButton", ExifFormat::U32, 1)
        .add_field(2064, "LensFunc1ButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2066, "LensFunc2ButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2068, "PlaybackButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2070, "BracketButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(2072, "FlashModeButtonPlaybackMode", ExifFormat::U32, 1)
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(6, "ExternalFlashFirmware", ExifFormat::U8, 2)
        // .add_bit_field(9, "FlashControlMode", 0x7f, 1) // TODO: Implement bit field support
        .add_field(11, "FlashFocalLength", ExifFormat::U32, 1)
        .add_field(12, "RepeatingFlashRate", ExifFormat::U32, 1)
        .add_field(13, "RepeatingFlashCount", ExifFormat::U32, 1)
        .add_field(14, "FlashGNDistance", ExifFormat::U32, 1)
        .add_field(15, "FlashGroupAControlMode", ExifFormat::U32, 1)
        .add_field(16, "FlashGroupBControlMode", ExifFormat::U32, 1)
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(6, "ExternalFlashFirmware", ExifFormat::U8, 2)
        // .add_bit_field(9, "FlashControlMode", 0x7f, 1) // TODO: Implement bit field support
        .add_field(12, "FlashFocalLength", ExifFormat::U32, 1)
        .add_field(13, "RepeatingFlashRate", ExifFormat::U32, 1)
        .add_field(14, "RepeatingFlashCount", ExifFormat::U32, 1)
        .add_field(15, "FlashGNDistance", ExifFormat::U32, 1)
        // .add_bit_field( // TODO: Implement bit field support
        // // .add_field(16, "FlashGroupAControlMode", 0xXX, X) // TODO: bit field // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(17, "FlashGroupBControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(17, "FlashGroupCControlMode", 0xXX, X) // TODO: bit field
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(6, "ExternalFlashFirmware", ExifFormat::U8, 2)
        // .add_bit_field(9, "FlashControlMode", 0x7f, 1) // TODO: Implement bit field support
        .add_field(12, "FlashFocalLength", ExifFormat::U32, 1)
        .add_field(13, "RepeatingFlashRate", ExifFormat::U32, 1)
        .add_field(14, "RepeatingFlashCount", ExifFormat::U32, 1)
        .add_field(15, "FlashGNDistance", ExifFormat::U32, 1)
        .add_field(16, "FlashColorFilter", ExifFormat::U32, 1)
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(17, "FlashGroupAControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupBControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupCControlMode", 0xXX, X) // TODO: bit field
        .add_field(27, "ExternalFlashCompensation", ExifFormat::U8, 1)
        .add_field(29, "FlashExposureComp3", ExifFormat::U8, 1)
        .add_field(39, "FlashExposureComp4", ExifFormat::U8, 1)
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(6, "ExternalFlashFirmware", ExifFormat::U8, 2)
        // .add_bit_field(9, "FlashControlMode", 0x7f, 1) // TODO: Implement bit field support
        .add_field(12, "FlashFocalLength", ExifFormat::U32, 1)
        .add_field(13, "RepeatingFlashRate", ExifFormat::U32, 1)
        .add_field(14, "RepeatingFlashCount", ExifFormat::U32, 1)
        .add_field(15, "FlashGNDistance", ExifFormat::U32, 1)
        .add_field(16, "FlashColorFilter", ExifFormat::U32, 1)
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(17, "FlashGroupAControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupBControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupCControlMode", 0xXX, X) // TODO: bit field
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(6, "ExternalFlashFirmware", ExifFormat::U8, 2)
        .add_field(10, "FlashCompensation", ExifFormat::U8, 1)
        .add_field(12, "FlashFocalLength", ExifFormat::U32, 1)
        .add_field(13, "RepeatingFlashRate", ExifFormat::U32, 1)
        .add_field(14, "RepeatingFlashCount", ExifFormat::U32, 1)
        .add_field(15, "FlashGNDistance", ExifFormat::U32, 1)
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(17, "FlashGroupAControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupBControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupCControlMode", 0xXX, X) // TODO: bit field
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(6, "ExternalFlashFirmware", ExifFormat::U8, 2)
        // .add_bit_field(9, "FlashControlMode", 0x7f, 1) // TODO: Implement bit field support
        .add_field(10, "FlashCompensation", ExifFormat::U8, 1)
        // Condition: $$self{FlashControlMode} == 0x01 or $$self{FlashControlMode} == 0x02
        .add_field(13, "RepeatingFlashRate", ExifFormat::U32, 1)
        .add_field(14, "RepeatingFlashCount", ExifFormat::U32, 1)
        .add_field(15, "FlashGNDistance", ExifFormat::U32, 1)
        .add_field(16, "FlashColorFilter", ExifFormat::U32, 1)
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(17, "FlashGroupAControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupBControlMode", 0xXX, X) // TODO: bit field
        // .add_bit_field( // TODO: Implement bit field support
        // .add_field(18, "FlashGroupCControlMode", 0xXX, X) // TODO: bit field
        .add_field(33, "FlashOutput", ExifFormat::U32, 1)
        // Condition: $$self{FlashControlMode} >= 0x06
        .add_field(38, "FlashFocalLength", ExifFormat::U32, 1)
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .add_field(0, "MultiExposureVersion", ExifFormat::Ascii, 4)
        .add_field(2, "MultiExposureShots", ExifFormat::U32, 1)
        .add_field(3, "MultiExposureAutoGain", ExifFormat::U32, 1)
        .add_field(0, "MultiExposureVersion", ExifFormat::Ascii, 4)
        .add_field(2, "MultiExposureShots", ExifFormat::U32, 1)
        .add_field(0, "HDRInfoVersion", ExifFormat::Ascii, 4)
        .add_field(0, "HDRInfoVersion", ExifFormat::Ascii, 4)
        .add_field(0, "LocationInfoVersion", ExifFormat::Undefined, 4)
        .add_field(5, "CountryCode", ExifFormat::Undefined, 3)
        .add_field(8, "POILevel", ExifFormat::U32, 1)
        .add_field(0, "FirmwareVersion51", ExifFormat::Ascii, 8)
        .add_field(10, "NEFCompression", ExifFormat::U16, 1)
        .add_field(0, "FirmwareVersion56", ExifFormat::Ascii, 4)
        .add_field(4, "BurstGroupID", ExifFormat::U16, 1)
        .add_field(0, "DistortionCorrectionVersion", ExifFormat::Ascii, 4)
        .add_field(20, "RadialDistortionCoefficient1", ExifFormat::SignedRational, 1)
        .add_field(28, "RadialDistortionCoefficient2", ExifFormat::SignedRational, 1)
        .add_field(36, "RadialDistortionCoefficient3", ExifFormat::SignedRational, 1)
        .add_field(0, "VignetteCorrectionVersion", ExifFormat::Ascii, 4)
        .add_field(36, "VignetteCoefficient1", ExifFormat::SignedRational, 1)
        .add_field(52, "VignetteCoefficient2", ExifFormat::SignedRational, 1)
        .add_field(68, "VignetteCoefficient3", ExifFormat::SignedRational, 1)
        .add_field(0, "Make", ExifFormat::Ascii, 24)
        .add_field(24, "Model", ExifFormat::Ascii, 8)
        .add_field(38, "ExposureTime", ExifFormat::U32, 1)
        .add_field(42, "FNumber", ExifFormat::Rational, 1)
        .add_field(50, "ExposureCompensation", ExifFormat::SignedRational, 1)
        .add_field(72, "FocalLength", ExifFormat::Rational, 1)
        .add_field(175, "Software", ExifFormat::Ascii, 16)
        .add_field(223, "ISO", ExifFormat::U16, 1)
        .add_field(1, "MakerNoteType", ExifFormat::U32, 1)
        .add_field(2, "MakerNoteVersion", ExifFormat::U8, 1)
        .add_field(3, "Make", ExifFormat::U32, 1)
        .add_field(4, "Model", ExifFormat::U32, 1)
        .add_field(5, "Software", ExifFormat::Undefined, 1)
        .add_field(6, "Equipment", ExifFormat::U32, 1)
        .add_field(11, "MaxApertureValue", ExifFormat::Rational, 1)
        .add_field(13, "Nikon_AVITags_0x000d", ExifFormat::U16, 1)
        .add_field(14, "Nikon_AVITags_0x000e", ExifFormat::U16, 1)
        .add_field(15, "FocalLength", ExifFormat::Rational, 1)
        .add_field(1, "None", ExifFormat::U32, 1)
        .add_field(2, "inches", ExifFormat::U32, 1)
        .add_field(3, "cm", ExifFormat::U32, 1)
        .add_field(21, "Nikon_AVITags_0x0015", ExifFormat::U16, 1)
        .add_field(22, "Duration", ExifFormat::Rational, 1)
        .add_field(23, "Nikon_AVITags_0x0017", ExifFormat::U16, 1)
        .add_field(24, "FocusMode", ExifFormat::U32, 1)
        .add_field(25, "Nikon_AVITags_0x0019", ExifFormat::I32, 1)
        .add_field(27, "DigitalZoom", ExifFormat::Rational, 1)
        .add_field(28, "Nikon_AVITags_0x001c", ExifFormat::Rational, 1)
        .add_field(29, "ColorMode", ExifFormat::U32, 1)
        .add_field(30, "Sharpness", ExifFormat::U32, 1)
        .add_field(31, "WhiteBalance", ExifFormat::U32, 1)
        .add_field(32, "NoiseReduction", ExifFormat::U32, 1)
        .add_field(32794, "Nikon_AVITags_0x801a", ExifFormat::I32, 1)
        .add_field(1, "Make", ExifFormat::U32, 1)
        .add_field(2, "Model", ExifFormat::U32, 1)
        .add_field(3, "Software", ExifFormat::U32, 1)
        .add_field(19, "FrameCount", ExifFormat::U32, 1)
        .add_field(4115, "ElectronicVR", ExifFormat::U32, 1)
        .add_field(17859226, "ExposureTime", ExifFormat::U32, 1)
        .add_field(17859229, "FNumber", ExifFormat::U32, 1)
        .add_field(17863172, "ExposureCompensation", ExifFormat::U32, 1)
        .add_field(17863178, "FocalLength", ExifFormat::U32, 1)
        .add_field(17867825, "SerialNumber", ExifFormat::U32, 1)
        .add_field(17867826, "LensInfo", ExifFormat::U32, 1)
        .add_field(17867827, "LensMake", ExifFormat::U32, 1)
        .add_field(17867828, "LensModel", ExifFormat::U32, 1)
        .add_field(17867829, "LensSerialNumber", ExifFormat::U32, 1)
        .add_field(0, "Above Sea Level", ExifFormat::U32, 1)
        .add_field(1, "Below Sea Level", ExifFormat::U32, 1)
        .add_field(33554433, "MakerNoteVersion", ExifFormat::U32, 1)
        .add_field(33554437, "WhiteBalance", ExifFormat::U32, 1)
        .add_field(33554439, "FocusMode", ExifFormat::U32, 1)
        .add_field(33554443, "WhiteBalanceFineTune", ExifFormat::U32, 1)
        .add_field(33554459, "CropHiSpeed", ExifFormat::U32, 1)
        .add_field(33554495, "WhiteBalanceFineTune", ExifFormat::U32, 1)
        .add_field(33554563, "LensType", ExifFormat::U32, 1)
        .add_field(33554599, "ShutterCount", ExifFormat::U32, 1)
        .add_field(33554603, "VariProgram", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoD850
/// Source lines: 8197-8251
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod850_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD850", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .build()
}

/// Binary data table: ShotInfoD4
/// Source lines: 8295-8323
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod4_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD4", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .build()
}

/// Binary data table: ShotInfoD4S
/// Source lines: 8326-8614
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfod4s_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoD4S", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 5)
        .add_field(0, "Reset", ExifFormat::U8, 1)
        .add_field(1, "Zoom", ExifFormat::U8, 1)
        .add_field(3, "None", ExifFormat::U8, 1)
        .build()
}

/// Binary data table: ShotInfoZ6III
/// Source lines: 8617-8677
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfoz6iii_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoZ6III", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(136, "OrientationOffset", ExifFormat::U32, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96
        .build()
}

/// Binary data table: ShotInfoZ7II
/// Source lines: 8680-8762
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfoz7ii_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoZ7II", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(48, "IntervalOffset", ExifFormat::U32, 1)
        .add_field(56, "PortraitOffset", ExifFormat::U32, 1)
        .add_field(136, "OrientationOffset", ExifFormat::U32, 1)
        // Condition: $$self{Model} =~ /^NIKON Z f\b/i
        .add_field(152, "OrientationOffset", ExifFormat::U32, 1)
        // Condition: $$self{Model} =~ /^NIKON Z (30|5|50|6|6_2|7|7_2|8|fc)\b/i
        .build()
}

/// Binary data table: ShotInfoZ8
/// Source lines: 8829-8905
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfoz8_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoZ8", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: ShotInfoZ9
/// Source lines: 8908-9033
/// Process function: ProcessNikonEncrypted
pub fn create_shotinfoz9_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("ShotInfoZ9", ExifFormat::U8)
        // .encrypted(true) // TODO: Implement encryption support
        .add_field(0, "ShotInfoVersion", ExifFormat::Ascii, 4)
        .add_field(4, "FirmwareVersion", ExifFormat::Ascii, 8)
        .add_field(14, "FirmwareVersion2", ExifFormat::Ascii, 8)
        .add_field(24, "FirmwareVersion3", ExifFormat::Ascii, 8)
        .add_field(36, "NumberOffsets", ExifFormat::U32, 1)
        .add_field(42, "IntervalFrame", ExifFormat::U16, 1)
        // Condition: $$self{ShutterMode} and $$self{ShutterMode} ne 96 and $$self{IntervalShooting} > 0
        .build()
}

/// Binary data table: FlashInfoUnknown
/// Source lines: 11856-11864
/// Process function: ProcessBinaryData
pub fn create_flashinfounknown_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("FlashInfoUnknown", ExifFormat::U8)
        .add_field(0, "FlashInfoVersion", ExifFormat::Ascii, 4)
        .build()
}

/// Binary data table: MultiExposure
/// Source lines: 11867-11890
/// Process function: ProcessBinaryData
pub fn create_multiexposure_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("MultiExposure", ExifFormat::U32)
        .add_field(0, "MultiExposureVersion", ExifFormat::Ascii, 4)
        .add_field(2, "MultiExposureShots", ExifFormat::U32, 1)
        .add_field(3, "MultiExposureAutoGain", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: MultiExposure2
/// Source lines: 11893-11920
/// Process function: ProcessBinaryData
pub fn create_multiexposure2_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("MultiExposure2", ExifFormat::U32)
        .add_field(0, "MultiExposureVersion", ExifFormat::Ascii, 4)
        .add_field(2, "MultiExposureShots", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: MOV
/// Source lines: 12158-12217
/// Process function: ProcessBinaryData
pub fn create_mov_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("MOV", ExifFormat::U8)
        .add_field(0, "Make", ExifFormat::Ascii, 24)
        .add_field(24, "Model", ExifFormat::Ascii, 8)
        .add_field(38, "ExposureTime", ExifFormat::U32, 1)
        .add_field(42, "FNumber", ExifFormat::Rational, 1)
        .add_field(50, "ExposureCompensation", ExifFormat::SignedRational, 1)
        .add_field(72, "FocalLength", ExifFormat::Rational, 1)
        .add_field(175, "Software", ExifFormat::Ascii, 16)
        .add_field(223, "ISO", ExifFormat::U16, 1)
        .build()
}

