// AUTO-GENERATED by exiftool_sync extract binary-formats
// Source: third-party/exiftool/lib/Image/ExifTool/Olympus.pm
// Generated by exiftool_sync extract binary-formats
// DO NOT EDIT - Regenerate with `cargo run --bin exiftool_sync extract binary-formats`

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Olympus.pm"]

use crate::core::binary_data::{BinaryDataTable, BinaryDataTableBuilder};
use crate::core::types::ExifFormat;

/// Binary data table: Thumbnail
/// Source lines: 3810-3819
/// Process function: ProcessBinaryData
pub fn create_thumbnail_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("Thumbnail", ExifFormat::U32)
        .add_field(1, "ThumbnailWidth", ExifFormat::U32, 1)
        .add_field(2, "ThumbnailHeight", ExifFormat::U32, 1)
        .add_field(3, "ThumbnailLength", ExifFormat::U32, 1)
        .add_field(4, "ThumbnailOffset", ExifFormat::U32, 1)
        .build()
}

/// Binary data table: WAV
/// Source lines: 3940-4010
/// Process function: ProcessBinaryData
pub fn create_wav_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("WAV", ExifFormat::U8)
        .add_field(522, "Index01", ExifFormat::U8, 1)
        .add_field(532, "Index02", ExifFormat::U8, 1)
        .add_field(542, "Index03", ExifFormat::U8, 1)
        .add_field(552, "Index04", ExifFormat::U8, 1)
        .add_field(562, "Index05", ExifFormat::U8, 1)
        .add_field(572, "Index06", ExifFormat::U8, 1)
        .add_field(582, "Index07", ExifFormat::U8, 1)
        .add_field(592, "Index08", ExifFormat::U8, 1)
        .add_field(602, "Index09", ExifFormat::U8, 1)
        .add_field(612, "Index10", ExifFormat::U8, 1)
        .add_field(622, "Index11", ExifFormat::U8, 1)
        .add_field(632, "Index12", ExifFormat::U8, 1)
        .add_field(642, "Index13", ExifFormat::U8, 1)
        .add_field(652, "Index14", ExifFormat::U8, 1)
        .add_field(662, "Index15", ExifFormat::U8, 1)
        .add_field(672, "Index16", ExifFormat::U8, 1)
        .build()
}

