// AUTO-GENERATED by exiftool_sync extract binary-formats
// Source: third-party/exiftool/lib/Image/ExifTool/Pentax.pm
// Generated by exiftool_sync extract binary-formats
// DO NOT EDIT - Regenerate with `cargo run --bin exiftool_sync extract binary-formats`

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Pentax.pm"]

use crate::core::binary_data::{BinaryDataTable, BinaryDataTableBuilder};
use crate::core::types::ExifFormat;

/// Binary data table: MOV
/// Source lines: 6031-6078
/// Process function: ProcessBinaryData
pub fn create_mov_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("MOV", ExifFormat::U8)
        .add_field(0, "Auto", ExifFormat::U8, 1)
        .add_field(1, "Daylight", ExifFormat::U8, 1)
        .add_field(2, "Shade", ExifFormat::U8, 1)
        .add_field(4, "Tungsten", ExifFormat::U8, 1)
        .add_field(5, "Manual", ExifFormat::U8, 1)
        .build()
}

/// Binary data table: PENT
/// Source lines: 6146-6313
/// Process function: ProcessBinaryData
pub fn create_pent_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("PENT", ExifFormat::U8)
        .add_field(0, "Above Sea Level", ExifFormat::U8, 1)
        .add_field(1, "Below Sea Level", ExifFormat::U8, 1)
        .add_field(2, "2-Dimensional Measurement", ExifFormat::U8, 1)
        .add_field(3, "3-Dimensional Measurement", ExifFormat::U8, 1)
        .build()
}

