// AUTO-GENERATED by exiftool_sync extract binary-formats
// Source: third-party/exiftool/lib/Image/ExifTool/Sigma.pm
// Generated by exiftool_sync extract binary-formats
// DO NOT EDIT - Regenerate with `cargo run --bin exiftool_sync extract binary-formats`

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Sigma.pm"]

use crate::core::binary_data::{BinaryDataTable, BinaryDataTableBuilder};
use crate::core::types::ExifFormat;

/// Binary data table: WBSettings
/// Source lines: 834-851
/// Process function: ProcessBinaryData
pub fn create_wbsettings_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("WBSettings", ExifFormat::F32)
        .add_field(0, "WB_RGBLevelsAuto", ExifFormat::F32, 3)
        .add_field(3, "WB_RGBLevelsDaylight", ExifFormat::F32, 3)
        .add_field(6, "WB_RGBLevelsShade", ExifFormat::F32, 3)
        .add_field(9, "WB_RGBLevelsOvercast", ExifFormat::F32, 3)
        .add_field(12, "WB_RGBLevelsIncandescent", ExifFormat::F32, 3)
        .add_field(15, "WB_RGBLevelsFluorescent", ExifFormat::F32, 3)
        .add_field(18, "WB_RGBLevelsFlash", ExifFormat::F32, 3)
        .add_field(21, "WB_RGBLevelsCustom1", ExifFormat::F32, 3)
        .add_field(24, "WB_RGBLevelsCustom2", ExifFormat::F32, 3)
        .add_field(27, "WB_RGBLevelsCustom3", ExifFormat::F32, 3)
        .build()
}

/// Binary data table: WBSettings2
/// Source lines: 854-871
/// Process function: ProcessBinaryData
pub fn create_wbsettings2_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("WBSettings2", ExifFormat::F32)
        .add_field(0, "WB_RGBLevelsUnknown0", ExifFormat::F32, 3)
        .add_field(3, "WB_RGBLevelsUnknown1", ExifFormat::F32, 3)
        .add_field(6, "WB_RGBLevelsUnknown2", ExifFormat::F32, 3)
        .add_field(9, "WB_RGBLevelsUnknown3", ExifFormat::F32, 3)
        .add_field(12, "WB_RGBLevelsUnknown4", ExifFormat::F32, 3)
        .add_field(15, "WB_RGBLevelsUnknown5", ExifFormat::F32, 3)
        .add_field(18, "WB_RGBLevelsUnknown6", ExifFormat::F32, 3)
        .add_field(21, "WB_RGBLevelsUnknown7", ExifFormat::F32, 3)
        .add_field(24, "WB_RGBLevelsUnknown8", ExifFormat::F32, 3)
        .add_field(27, "WB_RGBLevelsUnknown9", ExifFormat::F32, 3)
        .build()
}

