// AUTO-GENERATED by exiftool_sync extract binary-formats
// Source: third-party/exiftool/lib/Image/ExifTool/Sony.pm
// Generated by exiftool_sync extract binary-formats
// DO NOT EDIT - Regenerate with `cargo run --bin exiftool_sync extract binary-formats`

#![doc = "EXIFTOOL-SOURCE: lib/Image/ExifTool/Sony.pm"]

use crate::core::binary_data::{BinaryDataTable, BinaryDataTableBuilder};
use crate::core::types::ExifFormat;

/// Binary data table: PIC
/// Source lines: 10443-10838
/// Process function: ProcessSonyPIC
pub fn create_pic_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("PIC", ExifFormat::U8)
        .add_field(12, "JpgFromRawLength", ExifFormat::U32, 1)
        .add_field(22, "SonyImageWidth", ExifFormat::U16, 1)
        .add_field(24, "SonyImageHeight", ExifFormat::U16, 1)
        .add_field(0, "Horizontal (normal)", ExifFormat::U8, 1)
        .add_field(2, "Rotate 180", ExifFormat::U8, 1)
        .add_field(8, "Snap Shot", ExifFormat::U8, 1)
        .add_field(23, "Standard", ExifFormat::U8, 1)
        .add_field(51, "Fine", ExifFormat::U8, 1)
        .add_field(52, "Comment", ExifFormat::AsciiString, 19)
        .add_field(1550, "Sony_rtmd_0x060e", ExifFormat::U8, 1)
        .add_field(12816, "Sony_rtmd_0x3210", ExifFormat::U8, 1)
        .add_field(12825, "Sony_rtmd_0x3219", ExifFormat::U8, 1)
        .add_field(12826, "Sony_rtmd_0x321a", ExifFormat::U8, 1)
        .add_field(33024, "Sony_rtmd_0x8100", ExifFormat::U8, 1)
        .add_field(2, "2-Dimensional Measurement", ExifFormat::U8, 1)
        .add_field(3, "3-Dimensional Measurement", ExifFormat::U8, 1)
        .add_field(1, "Incandescent", ExifFormat::U8, 1)
        .add_field(2, "Fluorescent", ExifFormat::U8, 1)
        .add_field(4, "Daylight", ExifFormat::U8, 1)
        .add_field(5, "Cloudy", ExifFormat::U8, 1)
        .add_field(255, "Preset", ExifFormat::U8, 1)
        .add_field(0, "Sony:FocusPosition", ExifFormat::U8, 1)
        .add_field(1, "FocalLength", ExifFormat::U8, 1)
        .add_field(0, "Sony:FocusPosition2", ExifFormat::U8, 1)
        .add_field(1, "FocalLengthIn35mmFormat", ExifFormat::U8, 1)
        .add_field(0, "Sony:GPSDateStamp", ExifFormat::U8, 1)
        .add_field(1, "Sony:GPSTimeStamp", ExifFormat::U8, 1)
        .add_field(0, "Sony:GPSLatitude", ExifFormat::U8, 1)
        .add_field(1, "Sony:GPSLatitudeRef", ExifFormat::U8, 1)
        .add_field(0, "Sony:GPSLongitude", ExifFormat::U8, 1)
        .add_field(1, "Sony:GPSLongitudeRef", ExifFormat::U8, 1)
        .add_field(0, "Sony:HiddenDataOffset", ExifFormat::U8, 1)
        .add_field(1, "Sony:HiddenDataLength", ExifFormat::U8, 1)
        .build()
}

/// Binary data table: PMP
/// Source lines: 10484-10578
/// Process function: ProcessBinaryData
pub fn create_pmp_table() -> BinaryDataTable {
    BinaryDataTableBuilder::new("PMP", ExifFormat::U8)
        .add_field(12, "JpgFromRawLength", ExifFormat::U32, 1)
        .add_field(22, "SonyImageWidth", ExifFormat::U16, 1)
        .add_field(24, "SonyImageHeight", ExifFormat::U16, 1)
        .add_field(0, "Horizontal (normal)", ExifFormat::U8, 1)
        .add_field(2, "Rotate 180", ExifFormat::U8, 1)
        .add_field(8, "Snap Shot", ExifFormat::U8, 1)
        .add_field(23, "Standard", ExifFormat::U8, 1)
        .add_field(51, "Fine", ExifFormat::U8, 1)
        .add_field(52, "Comment", ExifFormat::AsciiString, 19)
        .build()
}

